### ISSUE TITLE
[DevOps] Panics currently don't trigger alerts.

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#1016]
When a background thread panics in our application, it does not currently trigger alerts with the panic. Instead we *may* get an alert that auctions are not being processed.

**Comment by e00E** [comment]
I'm guessing we can set up kubernetes to complain if any solver container exits on it's own since that should never happen.
Previously we caught some instances of crash on start up because of the alert "pod is restarting frequently".

**Comment by e00E** [comment]
I see, the problem is that the program doesn't exit because it's just a thread panic.

**Comment by nlordell** [comment]
Yes, its an issue specifically with background threads.

**Comment by fleupold** [comment]
We can set up alerts based on regex in the logs (we can search for panic) similar to [this MR](https://gitlab.gnosisdev.com/devops/gnosis-staging/merge_requests/187/diffs)

**Comment by fleupold** [comment]
Nvm, didn't see the PR before, that works too. However it requires us remembering to print an error in all threaded components.

**Comment by nlordell** [comment]
> However it requires us remembering to print an error in all threaded components.

Thats a good point, my only minor concern is that the format of panic messages is not well specified and can unexpectedly change with Rust versions.

Now that I think about it, maybe we can setup a custom panic handler that logs instead of printing to std::err? I'll look into the viability of this.
