### ISSUE TITLE
Optimize the price estimator docker image

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#1027]
We could try using a very small linux distro like alpine with musl to decrease the container size.

This isn't important, just nice to have.

**Comment by fleupold** [comment]
With these kind of tasks (small but low pri) I worry that unless we do this at the get-go we are never going to do it, but looking forward to be proven wrong 😄

**Comment by e00E** [comment]
I've looked into this but ran into the issue that one of our dependencies does not compile:

> error: cannot produce proc-macro for derive_more v0.99.5 as the target x86_64-unknown-linux-musl does not support these crate types

https://github.com/rust-lang/cargo/issues/7154 :

> I think the issue is that rustc for musl does not support dynamic linking. Proc-macros have to be dynamic libraries as they are loaded by rustc.

There is a workaround but at this point I prefer not introducing more complexity over having a smaller image.

**Comment by nlordell** [comment]
I'm going to reopen this to take a stab at it tomorrow. The advantage of building for musl is that you don't have a libc dependency, so theoretically you can build it in Travis and then copy the binary over to the image (and not have a builder image).

Ultimately I think this will might make the build process easier (no double docker image) and have a smaller image.

**Comment by e00E** [comment]
In that case, could we try to do the same thing for the driver binary? With the same argument it should end up making that image simpler too (totally static binary).

**Comment by nlordell** [comment]
I think so. It would make it so the OS version on Travis matter less. One thing to note is that for now, we will still need to depend on the solver image because of its optimization libraries (from what I understand).

**Comment by nlordell** [comment]
Cross compiling openssl to musl is so hard... :sob:
