### ISSUE TITLE
Handle `atoms=false` (should be default)

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#1082]
Since #1007 we have decimal information for all valid tokens available in rust. We should use this information to expose all price-estimation APIs in base units (where 1ETH == 1 instead of 10**18).

**Comment by fleupold** [comment]
We should also expose baseunits for the market route. EFrontier is trying to use it for their market making strategy and really struggling to do the conversion.

**Comment by e00E** [comment]
This is done.
