### ISSUE TITLE
Wrong Price Estimates

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#1083]
#1069 Collected some data around historic price estimates and compares them to the computed solution prices. Specifically it computed bid/ask spread for all token pairs included in a solution and compares it to the actual submitted price. As such, once all overlapping ring trades in an orderbook are removed, you would expect `best_bid < price < best_ask`. But this seems to not be the case around 6% of the time. 

In many cases, errors are small (fractions of a percent) and are probably caused by price rounding in the solver (which is not accounted for in the current historic price calculation implementation).  However, in some cases, these errors are bigger (~2-5%) which is much more significant and may cause bad user experiences with the price estimates. The main cause for this seems to be issues around how overlapping ring trades are reduced, specifically they are always reduced at limit exchange rates, which generally is not the optimal exchange rate for matching overlapping orders, and reducing orders at limit xrates can leave residual orders with "good" xrates in the reduced orderbook that contribute to lower xrate estimates.

This issue captures the work around quantifying the exact conditions that cause this as well as reducing this number down.

Note that there will always be some discrepancies, however, the hope is that the `pricegraph` will be able to generate bid/ask spreads such that `best_bid < price < best_ask` (although the spread may become less precise).

**Comment by fleupold** [comment]
Thanks for creating this task! Do I understand correctly, that the "direction" of the ring matters? 

This is, if there was a residual order o1 remaining that in the solver would have been matched completely, this order would not remain if we had settled the ring in the other direction (thus using o1 limit price, but potential leaving a different residual order o2).
If that's the case, would it be possible to take the minimum remaining amount from settling each ring in both ways?

**Comment by nlordell** [comment]
> Do I understand correctly, that the "direction" of the ring matters?

Yes it does, but "direction" here is more about the starting point (since this is a directed graph, and the reverse direction is not guaranteed to exist, or be a negative cycle).

> would it be possible to take the minimum remaining amount from settling each ring in both ways?

We would potentially have to do this for each starting point, but this is a nice idea. The other option I was toying with would be to remove all residual orders after reducing negative cycles, but I like your idea better. Additionally it may be possible to identify the "best" starting point so that the residual orders are only in the sell -> buy segment of the negative cycle (although at this point, its unclear to me whether or not this is possible - in fact I believe it is not).

To illustrate the issue with the starting points:

- Order 1: buy 0.5 token A for 1.0 token B
- Order 2: buy 0.5 token B for 1.0 token A

Here the pricegraph would find the ring `A --0.5-> B --0.5-> A`, which would have a transitive xrate of 0.25 (which would be negative in logarithmic scale). If we start at order 1, we would reduce the remaining amount by 1.0 B, which, at the limit xrate, would buy 0.5 A. We would then reduce order 2's remaining amount by the 0.5 A that was purchased with order 1. We would be left with:

- Order 2: buy 0.25 token B for 0.5 token A.

Conversely if we started at B, then after reducing we would be left with:

- Order 1: buy 0.25 token A for 0.5 token B.

When computing the price estimate for buying token A for token B, then the second scenario is less optimistic (since there will be no residual orders when computing the inverse counter transitive order buying B for A).

If we go with your suggestion, then both orders should be completely reduced, and we won't be left with any transitive orders :tada:.

**Comment by nlordell** [comment]
Closing this in favour of #1191. The metric for exchange rate estimates has changed with #1218 and requires some more analysis to understand the bad estimates 2% of the time and the skipped orders 5% of the time.
