### ISSUE TITLE
Improved Price Estimation Algorithm

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#1086]
Counter intuitively, it is possible for estimated buy amounts for larger sell amounts to be lower than if the sell amounts were smaller. This is because the pricegraph works by computing the **marginal exchange rate** in order to completely sell a certain volume. However, this is not entirely correct and can be modified so that this doesn't happen.

Consider the following scenario:
- Order 1: buy 100 OWL for 100 DAI
- Order 2: buy 1000 OWL for 100 DAI

Currently, when estimating the xrate for selling 150 OWL, the pricegraph algorithm will determine that 100 DAI can be bought for 100 OWL from order 1, and then the remaining 50 OWL must use order 2. Therefore, the marginal price will be 10 OWL for 1 DAI, and the the pricegraph will estimate the order "buy 15 DAI for 150 OWL".

However, the xrate can be capped by the previous buy amount. Specifically the order "buy 100 DAI for 150 OWL" also overlaps with order 1 and is a much better xrate estimate that is also matchable and less counter intuitive.

**Comment by nlordell** [comment]
## Improved Price Estimation Algorithm

Currently, prices are estimated by computing the marginal exchange for trading the last &epsilon; of some token over a token pair. This method is unnecessarily pessimistic and can be improved by instead computing the maximum buy volume for a given sell volume. To better illustrate the new approach, here is an example:

Consider the following orderbook:
```
   /---8:1---\
  /----4:1----\
 /----20:10----\
 |             v
T1             T2
```

That is, there are 3 transitive orders:
- Order 1 buying 20 T1 and selling 10 T2 (limit price of 2.0)
- Order 2 buying 4 T1 and selling 1 T2 (limit price of 4.0)
- Order 3 buying 8 T1 and selling 1 T2 (limit price of 8.0)

The problem to solve being: What is the *best* (highest) limit price can be used for my order buying T2 and selling *x* T1 such that my order will be fully overlapping (and likely matched by the solver).

Here is a graphical representation of the available buy volume at the limit exchange rates:

![image](https://user-images.githubusercontent.com/4210206/87925785-13ccc400-ca81-11ea-8596-7ca4a29992c3.png)

### Legacy Limit Price

The legacy price estimation would use the available transitive orders from most favourable to least favourable order (i.e. from lowest limit price to highest limit price) until the sell amount *x* of T1 is fully used. The inverse of limit price the last counter transitive order would then be the final result.

As expected, the resulting limit price would be monotonically decreasing with increasing sell volume *x* of T1. The following graph captures the resulting price estimate in function of sell amount (ignoring fees):

![image](https://user-images.githubusercontent.com/4210206/87924361-17f7e200-ca7f-11ea-9109-0f6d7d8e0b20.png)

The resulting chart shows the limit price estimates in function of *x*. As expected, for *x* between `0` and `20`, the limit price estimate will be the inverse of the "best" counter order - `1/2 = 0.5`. Between `20` and `24`the limit price estimate will be inverse of the second "best" order - `1/4 = 0.25`, and between `24` and `32`, `1/8 = 0.125`. Finally, once we try to sell *x* greater than the sum of all sell amounts for all transitive orders, the `pricegraph` will not produce a price estimate (in the graph this appears as `0`).

While price estimates produced this way should be sufficiently pessimistic so that the solver can match these orders, it is unnecessarily so. Additionally, it produces some counter-intuitive results when we consider the buy amounts that can be bought:

![image](https://user-images.githubusercontent.com/4210206/87925601-d0725580-ca80-11ea-9838-ef12f3f9c1dc.png)

These results are not really intuitive, since the estimated buy amounts are not monotonically increasing with sell amounts as one would expect. In fact, if you consider selling `20` T1, then the estimated limit price would be `0.5`, however <code>20 + &epsilon;</code> the price jumps to `0.25`. However, it would actually be more beneficial to just buy the available `10` T2 liquidity at a slightly lower price for <code>20 + &epsilon;</code> T1. That would yield a price estimate of <code>0.5 + &epsilon;/2</code>

### New Price Estimation Process

The proposed change is to instead track the maximum buy volume per sell volume *x* given the counter transitive orders limit prices. Specifically,  for *x* between `0` and `20`, the best counter order limit price is `0.5`, meaning that the maximum buy would be between `0` and `10`, growing linearly with *x*. Now, for *x* between `10` and `40`, the maximum T2 buy volume remains `10`, since using any of the available T2 liquidity from order 2 or 3 would make us buy **less** (for example, at 30 sell volume if we fully use the liquidity from order 2, using 4 of the sell volume, and then with the remaining 26 sell volume liquidity from order 1, the total buy volume would be `1 + 26/4 = 7.5 < 10`, because of uniform clearing prices). Extrapolating we get the following maximum buy volume in function of the sell volume:

![image](https://user-images.githubusercontent.com/4210206/87927271-41b30800-ca83-11ea-97a2-5d4d159d1307.png)

Notice how the placed orders limit buy volume is no **monotonically increasing** with sell volume :tada:. This can easily be converted into limit prices yielding:

![image](https://user-images.githubusercontent.com/4210206/87927478-8d65b180-ca83-11ea-8b7b-87de06ba0d61.png)

### Comparison

Here are the charts comparing the price estimates (and estimated buy volume):

![image](https://user-images.githubusercontent.com/4210206/87927549-ac644380-ca83-11ea-98e4-248d8c34b184.png)

## Notes

One thing that I noticed when figuring out this new algorithm, is that, from a `pricegraph` perspective it is more natural to compute a minimum sell amount for a given buy amount. Additionally it might be nice to add a new route that doesn't just echo the input sell amount, since in many cases, you could get the same buy amount by selling less.

**Comment by e00E** [comment]
This makes sense to me. Let me summarize in my own words.

The new algorithm answers the question:
> Which order should I create when I want to sell at most X of token T1 and purchase as much as possible of token T2?

Whereas the old algorithm answers the question:
> Which order should I create when I want to sell exactly X of token T1 and purchase token T2.

Users care about buying as much as possible so they want to have an answer to the first question and not the second. While reading I also had the same thought as in your note: with an ui change we can inform users they can get the same buy amount for less sell amount than what they have specified.

**Comment by nlordell** [comment]
> The new algorithm answers the question:

Correct, that is the hope at least. 

> Whereas the old algorithm answers the question:
>
> > Which order should I create when I want to sell exactly X of token T1 and purchase token T2.

I think the question is more "after selling <code><i>x</i> - &epsilon;</code> of token T1, at what price would I be able to sell an additional <code>&epsilon;</code> of T1?". Although, we were trying to answer the same question, just using a worse approximation.

**Comment by fedgiac** [comment]
I really like the proposal and how it's written!

> The new algorithm answers the question:
>> Which order should I create when I want to sell at most X of token T1 and purchase as much as possible of token T2?

To my understanding, the new algorithm answers the question:
> Which order should I create when I want to sell **exactly** X of token T1 and purchase as much as possible of token T2?

That is because there is no attempt done anywhere to reduce the sold amount. The sold amount is always used in full. (The notes propose to change this though.)

The old algorithm answers the same question but with an extra assumption:
> Assuming that the final matching price must be the price of an existing order, ...

**Comment by nlordell** [comment]
> sell exactly X of token T1

This isn't true, because the solver is not required to fully match the sell amount.

**Comment by fedgiac** [comment]
I mean, according to the "New Price Estimation Process" described here, the price estimate would be computed under the assumption that the whole sold amount (`X`) is used up in the trade.
