### ISSUE TITLE
Default price estimator query parameters

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#1106]
@fleupold  suggested making the atoms parameters default to false instead of forcing it to be supplied.

> I would eventually like to see all the query params being optional (as otherwise they could arguably be part of the fixed route).

**Comment by e00E** [comment]
I weakly disagree with this. Whether `atoms` is true or false changes the result significantly. It is better to be explicit about this than to assume a default. Overall it's not important but I do think no default is better.

> as otherwise they could arguably be part of the fixed route

I don't know whether this is true or not but regardless it doesn't justify whether we should have a default or not. It just means we might have made a mistake previously not having it be part of the route.

**Comment by fleupold** [comment]
My reason is mostly convenience/ease of understanding the API. From other exchange APIs I have worked with so far (Kyber, SCP, Binance, Kraken, dex.AG) it appears standard to return prices and amounts in base units. The reason we didn't do this to begin with was that we didn't want to fetch token information on the server.

Keeping "atoms=true" as a non-standard feature seems fine (there might be arb scripts that want to compare tradable atoms between smart contracts and not query token info themselves) but it is in my opinion not common enough to require developers to actively think about it when trying to consume the API.

I can see your concern about the gravity of accidental mistakes and also don't feel strongly about this feature unless we get this feedback from other developers. 
Maybe we could return the unit (atoms, base units) in the result json to avoid accidental confusion.

**Comment by nlordell** [comment]
I'd also be inclined to default to base units. I would even go as far to suggest that it should be a `unit={atom,baseunit}` query parameter (`atoms=true` could remain supported for historic reasons).
