### ISSUE TITLE
Cannot fetch atom=false info for token 9

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#1170]
https://price-estimate-mainnet.dev.gnosisdev.com/api/v1/markets/9-4/estimated-buy-amount/10000?atoms=false

> {"message":"request with atoms=true for token we don't have erc20 info for"}

Is there something wrong with the hardcoded token info for this token? Other IDs (e.g. 7) work fine.

**Comment by nlordell** [comment]
From the error message, it suggests that token ID 7 does not have "decimals" information to compute the price estimate in base units.

**Comment by nlordell** [comment]
I did a little more digging and it appears that this is the `sUSD` token. Specifically, the registered token address is the sUSD proxy contract. I also was able to get the `decimals` information when following the proxy contract.

That being said, when I tried to use the new `getTokenInfo` viewer method, I get the following error:
```
truffle(mainnet)> const viewer = await BatchExchangeViewer.deployed()
truffle(mainnet)> await viewer.getTokenInfo(9)
Uncaught Error: Returned values aren't valid, did it run Out of Gas?
```

**Comment by nlordell** [comment]
Digging a little deeper, this happens because of:
```sol
    function setMessageSender(address sender) external onlyProxy {
        messageSender = sender;
    }
```

Which causes a "evm: write protection" because of the `STATICCALL`. Also, it required additional gas because of writing to storage.

I think this is probably a viewer contract issue, and since the viewer contract reverts the internal transaction, maybe we don't need to do a `STATICCALL` but can do a `CALL` instead?

**Comment by fleupold** [comment]
In that case we would need to make getTokenInfo be non-view which is a bit weird but could work. Let's move this discussion into dex-contracts then. For now, we should probably hardcode the info for both the old and new sUSD and SNX tokens in the TOKEN_DATA

**Comment by nlordell** [comment]
Closing as I created an MR in GitLab to set `TOKEN_DATA` on our staging price estimator.
