### ISSUE TITLE
Noop transaction did not go through because max gas price was low

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#1186]
Today we noticed in the logs that the noop transaction used to cancel the solution submission did not go through which caused a future solution submission to fail.

This was likely caused by the change that makes the gas price limited by calculated based on the earned fee of the solution. If this is low then the solution transaction does not go through and we send a cancel transaction with 12.5% higher gas price. If that price still isn't enough then the the transaction does not get cancelled.

One way to fix this is to always send the the noop transaction with some minimum gas price (like the "fast" estimate). On the other hand we could also argue that we do not need to fix this as this can only be a problem if the next solution also earns so little fees that the maximum gas price has not increased, so that solution cannot be worth submitting either.
Looking at it from this perspective the best solution imo is to not even attempt to submit the solution in the first place when the maximum gas price is below our estimate for "fast".

**Comment by nlordell** [comment]
> next solution also earns so little fees that the maximum gas price has not increased, so that solution cannot be worth submitting either.

The issue here is that the starting gas price for the solution might be lower than the noop gas price for cancelling the previous solution, but the capped gas price might be higher and high enough to get mined.

**Comment by nlordell** [comment]
Just a concrete example to illustrate what is happening: this cancellation no-op transaction was created with a gas price of ~3 gwei which is clearly not enough to get mined how. This price was chosen because of the small amount of earned fees.

![image](https://user-images.githubusercontent.com/4210206/88473218-99d28a00-cf1b-11ea-9a4e-3c9446c6792d.png)
