### ISSUE TITLE
Retry submitting solution during network congestion

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#1187]
Currently, when we receive a `There are too many transactions in the queue. You're transaction was dropped due to limit. Try increasing the fee` error from the node we stop trying to submit a solution but instead should probably retry submission with a higher gas amount (treat this error as a confirmation timeout error).

**Comment by e00E** [comment]
This fits well after the race condition fixes for solution submission. There we introduce a function "is_nonce_error" which determines which errors lead to increasing the gas price. This function can be generalized to include this error.
