### ISSUE TITLE
Start calculating early with open-solver, but submit only late

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#1230]
Unfortunately, the running time of the open solver is no longer constant. It varies heavily with the instances. Especially during sales, we see it.

Due to this reason, we have to start the open-solver earlier than in the past, in order to guarantee that a solution is found in time.
But in order to avoid unnecessary submission from the open-solver, which will likely be overwritten by other solvers, it would be great if the open solver would start calculating the solutions early, but only submit the solution if the other solvers don't find a solution within the first 3 mins. It will save us quite some gas costs.

**Comment by e00E** [comment]
Currently we have TARGET_START_SOLVE_TIME and SOLVER_TIME_LIMIT. To implement this in a generic way we could change SOLVER_TIME_LIMIT to TARGET_SUBMIT_SOLUTION_TIME. Then we would always start every solver at target start solve time (which would be the same 30s for every solver) but only submit the solution at the target submit solution time. So if a solver finishes faster than expected we wait (sleep) until then.
The target submit solution time is what we can stagger between solvers.

**Comment by nlordell** [comment]
Neat idea. I think for the standard and best-ring solvers, the `TARGET_SUBMIT_SOLUTION_TIME` should be "immediately" since for those two I think we want to submit the solution as soon as possible. It would be nice if the scheduler would be responsible for starting the `submitSolution` call with the discovered solution.

The refactor could also finally fix #707

**Comment by fleupold** [comment]
I think it would be good for the more sophisticated solvers to submit as early as possible to a) have a faster indication of the solution (e.g. if market makers want to hedge against their trades it's better to do that after 1 than after 4 minutes - even though they can only be certain after 4 minutes) and b) a longer time in the mem-pool might lead to more chances of inclusion in times of gas prices being close to the cap.

But still implementing it a generic way sounds good.
