### ISSUE TITLE
Don't keep retrying to fetch token info if there was a method error

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#1242]
There are a large number of tokens where we fail to retrieve the ERC20 info. On failure we do not cache anything so every time we update the a price source we will attempt to retrieve the info and fail. This is especially noticeable with the large number of "fake" tokens that got added today.
We should check whether the error is the result of not being able to reach the ethereum node, in which case we can retry. Or the result of an evm error. In that case it is unlikely to ever succeed so we should mark this token as failed and not attempt to retrieve it again.

**Comment by fleupold** [comment]
That's a very good observation and a great suggestion!
