### ISSUE TITLE
[Driver] Adjust commitment to underlying order data to include reserved accounts

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#125]
In order to prevent submission of solutions that are based on faulty order data (e.g. when a reorg adds/removes an order from the batch), we provide a commitment to the underlying data as part of the `applyAuction` method.

At the moment this function just verifies the order hash of non-reserved order match.

With reserved accounts we also have to match that the data used for those "micro batches" has not changed since the solver has been invoked.

We therefore need to provide commitment to the total order data, e.g.

```
sha(auctions[slot].shaHash, nonce_account_1, … nonce_account_50)
```

as part of applyAuction. This task captures computing that hash in the driver and providing it on contract invocation.

**Comment by josojo** [comment]
Please consider the PR from dex-contracts:
Modification of applyAuction for new account model #94 #111

for this task as well.
