### ISSUE TITLE
[Price Estimator] Allow to ignore certain addresses for price estimates

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#1252]
We received a specific feature request from Efficient Frontier to allow excluding orders of certain addresses from the price estimates.

This is so that they can avoid trading with themselves when checking for market opportunities. Their strategy will be to have some order with longer validity always in the exchange but at times place a "taker" order just before the end of the batch. That taker order should be based on price estimates that ignore their initial order.

**Comment by e00E** [comment]
They can ignore the price for an estimate (which I assume must make the price worse) but then when they place an order based on that place the solver is still going to match it anyway. Am I missing something?

**Comment by fleupold** [comment]
You are right, that the solver would match the order if it was placed. The idea is to not place it in the first place as the estimate would indicate no trading is possible at the target price.

A bit more context:

Let's say we have one market making strategy that is doing a long standing quote (valid over multiple batches) and only cancels the order if the projected loss from doing the trade is more than some threshold (e.g. the cost of sending a cancellation tx). Let's say this order is willing to buy ETH at $100. Let the second best offer be $99.

Let's say the same market maker also applies a "taking" strategy that if in the last minute of a batch there is volume to be traded at some centralized exchange's current price, they place an order doing that trade. Let's say the centralized exchange quotes ETH at $99.50 (not enough to invalidate but below their other strategy's price). If they query the price estimation, they will see that they can sell 1 ETH for $99.50 and so they would do the trade with themselves.

However, if they could exclude the address that is doing their first strategy, the price estimation would tell them there is 0 ETH tradable at $99.50

**Comment by e00E** [comment]
I don't think this works. Imagine the situation where they have that order buying for up to 100 and someone else has the same order. They use the new price estimator feature to exclude their own address and they get a price of 100 (from the other order). Now if they place their sell order at 99.50 they can still get matched with themself.
The price estimator feature would only help in the situation where they are the only sellers because then it would not show them the price at 100.

**Comment by fleupold** [comment]
You are right, that this does not prevent self trades in all cases. The main thing to avoid is to enter a trade where you are guaranteed to not provide any value by matching other people's liquidity. 
Another use case for this could be to assess the price levels without some subset of liquidity (e.g. excluding CMMs or a specific high rolling market maker). This hasn't been requested yet, whereas the former use case was a specific requirement.
