### ISSUE TITLE
Price Estimator Out Of Memory

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#1350]
It seems like a good idea to track this in an issue. The summary is that we've seen a few cases where the staging container got killed due to exceeding the memory limit. The memory graph itself doesn't show any spike so it is likely that this is happens in a quick burst.

Felix checked the Kibana logs of the nginx ingress service for the first request that returned a 502 or 503 error around the point where the container got killed. `GET /api/v1/markets/4-1?atoms=true&hops=2` . This seems like a normal frontend request to me and when I ran it locally I couldn't see anything special about it in terms of memory usage.

One idea I had for the out of memory was many parallel requests since we use potentially a couple of megabytes during the handling of a single request but we would have seen that in the ingress logs so I don't think this happened.

The other idea is a bug in our code where we allocate too much memory. This could be reserving too much in a vector or an infinite loop that allocates.
For example [this](https://github.com/gnosis/dex-services/blob/b6064498b76089b60d565b859308f4aa6a06db20/pricegraph/src/graph/shortest_paths.rs#L70) could be a problem if we had a bug that would cause a loop in the predecessor list. I added a debug assert for this and let fuzzing run for a while but it didn't hit it (and really fuzzing should notice this even without a debug assert because it would be an infinite loop and run out of memory).

Or it could some kind of weird interaction with how kubernetes measures memory. For example it is possible for a process to request a large amount of virtual memory without any physical memory backing it. So if there is some condition in which we or a dependency does that it could trigger kubernetes even though the container does not really use the memory and we wouldn't notice this locally. I thought of this because I remembered this part of the [clang address sanitizer documentation](https://clang.llvm.org/docs/AddressSanitizer.html#limitations):

> On 64-bit platforms AddressSanitizer maps (but not reserves) 16+ Terabytes of virtual address space. This means that tools like ulimit may not work as usually expected.

**Comment by e00E** [comment]
Nginx and kubernetes allow mirroring requests to a second test location: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#mirror

We could use this to get 1. more load on staging, 2. run a second price estimator with more asserts, more logs, something like that.

---

Warp does not seem to read large http get request bodies into memory when they aren't needed.  I tested this by creating a logging allocator:
```rust
thread_local! {
    pub static LOG: std::cell::Cell<bool> = std::cell::Cell::new(true);
}
struct MyAllocator;
unsafe impl std::alloc::GlobalAlloc for MyAllocator {
    unsafe fn alloc(&self, layout: std::alloc::Layout) -> *mut u8 {
        LOG.with(|log| {
            if log.get() {
                log.set(false);
                println!("alloc {}", layout.size());
                log.set(true);
            }
        });
        std::alloc::System.alloc(layout)
    }
    unsafe fn dealloc(&self, ptr: *mut u8, layout: std::alloc::Layout) {
        LOG.with(|log| {
            if log.get() {
                log.set(false);
                println!("dealloc {}", layout.size());
                log.set(true);
            }
        });
        std::alloc::System.dealloc(ptr, layout)
    }
}
#[global_allocator]
static GLOBAL: MyAllocator = MyAllocator;
```

and then making a request with 100 MB body

```rust
fn main() {
    use isahc::prelude::*;
    let mut body = Vec::new();
    body.resize(100_000_000, 0u8);
    let response = Request::get("http://localhost:8080/api/v1/markets/4-7/estimated-buy-amount/1")
        .body(body)
        .unwrap()
        .send();
    let _ = dbg!(response);
}
```

Even if warp did keep them in memory I believe our nginx setup already filters out large bodies through some default value of https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size .

**Comment by fleupold** [comment]
I was able to repro the issue using https://github.com/gnosis/dex-services/pull/1357 and running this query:

http://localhost:8080/api/v1/markets/4-1?atoms=true&blockNumber=10693853

It OOMs roughly 1/2 times.

The error is indeed in the line that @e00E suggested:

![Screen Shot 2020-08-26 at 17 19 46](https://user-images.githubusercontent.com/1200333/91322968-9eab8780-e7c0-11ea-988b-f9d5ae01fb1d.png)

We talked a little bit about it with @nlordell and @fedgiac (https://jamboard.google.com/d/1N3_mXRTsrxWWh9WDTz0qoeK6f8oKn-NlU2itnwuXyWs/viewer?f=0)

and saved the graph instance that is causing this:

[oom_graph.txt](https://github.com/gnosis/dex-services/files/5131221/oom_graph.txt)


Indeed there seems to be a cycle between 1 (WETH) and 78 (CREDIT) which doesn't get removed by bellman ford because it's not negative (but exactly 0).

We will resume tomorrow, trying to find a minimal unit test and seeing how we can tackle this problem. Our working hypothesis is that it has something to do with float rounding.

**Comment by e00E** [comment]
Has been fixed by https://github.com/gnosis/dex-services/pull/1374
