### ISSUE TITLE
Large allocation when writing event file to Disk

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#1352]
When profiling memory usage locally I can see a somewhat large allocation (64MB) when we write the event file to disk. Why this is not enough to cause an OOM this might become an issue in the future as the event file grows.

<img width="563" alt="Screen Shot 2020-08-21 at 14 34 45" src="https://user-images.githubusercontent.com/1200333/90892197-37a36280-e3bd-11ea-90a9-2e7762839ae4.png">

If possible, we should probably use a buffered write here.

**Comment by bh2smith** [comment]
This looks as if it would require adding such a feature to the bincode crate.
