### ISSUE TITLE
Pricegraph incorrectly reports price estimate for dust amounts.

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#1355]
This issue was reported by the FE team WRT GUSD where dust amounts were producing estimates inconsistently.

The issue was related to, using small GUSD amounts where the rounding buffer being applied was making either the sell amount of buy amount be rounded to 0.

In looking into this issue I found related problems around dust amounts and price estimates that need to be fixed in order to have consistent results for price estimates around dust amounts:
- [x] Some checks were being done on all transitive orders, and other only on significant transitive orders. Fixed by #1384 and #1386
- [x] Estimated prices and orders were not failing when the final order is a dust trade. Fixed by #1401

**Comment by fleupold** [comment]
@anxolin was mentioning today that we could also account for economic viability in our estimates given it is becoming a more prominent issue.

**Comment by anxolin** [comment]
It would be great, probably it will be disappointing at first (lot of liquidity will disappear), but at least we set expectations and users can check for consumable liquidity.

**Comment by nlordell** [comment]
> account for economic viability

THere is an open issue for this, so we should discuss there: #1024
