### ISSUE TITLE
Fuzzing OOM errors

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-services#1431]
I found two out-of-memory errors when running the fuzzing service locally. Files are attached.

[2020-09-18_oom-errors.zip](https://github.com/gnosis/dex-services/files/5246664/2020-09-18_oom-errors.zip)

**Comment by fleupold** [comment]
This seems like a pretty severe issue. I think we should prioritize fixing this.

**Comment by nlordell** [comment]
So I found the issue, this is actually "working as expected" in the sense that there is an unlimited order with near `U256::MAX` balance. This means that when building the transitive orderbook, there are up to `2^128` trades that get generated, causing an OOM error.
