### ISSUE TITLE
Upstream U256 <-> f64 conversion

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#1455]
We should upstream U256 <-> f64 conversion to either the `uint` or `primitive_types` crates.

**Comment by bh2smith** [comment]
So the PR needed to get this rolling has been merged into parity-common, but it doesn't look like there will be a new version of this crate published anytime soon (even though the previous version was published 6 months ago). I have attempted to update our repo by depending on the github master branch itself as 

```
primitive-types = { git = "https://github.com/paritytech/parity-common/tree/master/primitive-types", features = ["fp-conversion"] }
```
and was instructed to set the local env var ` CARGO_NET_GIT_FETCH_WITH_CLI=true` but am still confronted with

```
fatal: repository 'https://github.com/paritytech/parity-common/tree/master/primitive-types/' not found
```

In any case, we are almost there... kinda.
