### ISSUE TITLE
Investigate high memory usage while syncing orderbook from scratch

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#1506]

**Comment by nlordell** [comment]
For some context, it looks like the orderbook syncing is allocating a lot of memory.

Here is the price estimator memory usage when it syncs the orderbook:
![image](https://user-images.githubusercontent.com/4210206/97990615-823f5300-1de0-11eb-930f-e0e7a1e7420b.png)

Here is the price estimator memory usage when it uses one from disk (note that the events that persist in memory are the same in both cases, so I think its something related to the process of collecting the logs, not the actual logs themselves):
![image](https://user-images.githubusercontent.com/4210206/97990762-b581e200-1de0-11eb-87c4-891ef71ee677.png)

**Comment by nlordell** [comment]
@e00E This can be closed now as it was fixed with the streamed past logs API right?

**Comment by e00E** [comment]
Yes.
