### ISSUE TITLE
Dangerous Default Values for Economic Viability Configuration

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#1512]
Not sure if this has been discussed much, but the current default values for economic viability are:
```
    economic_viability_subsidy_factor: 10.0,
    economic_viability_min_avg_fee_factor: 1.1,
    static_min_avg_fee_per_order: Some(
        0,
    ),
    static_max_gas_price: Some(
        100000000000000000,
    ),
    economic_viability_strategy: Static,
```

Meaning: Static Strategy with 0 as the min average fee.

I consider this to be somewhat dangerous for a Naive user following a startup guide, say our tutorial, that chooses not to read into the "Advanced Configuration". For example, I was experimenting/testing running a solver today and started paying quite some gas money to fill a bunch of old dust orders.

Could we consider making the default values a bit less dangerous for the naive user?

**Comment by e00E** [comment]
Agree. We sould make default dynamic strategy with no subsidy.

**Comment by bh2smith** [comment]
So its actually the subsidy factor that is making this dangerous? Not the min average fee?

**Comment by bh2smith** [comment]
Also, I just noticed we are setting our default values what seems to be an unconventional way here

https://github.com/gnosis/dex-services/blob/0a78d01e81b9cdabace8f4eea4dc0169a0f508a6/driver/common.env#L6-L8

Wouldn't it make more sense to declare the defaults directly with the option specification?

**Comment by e00E** [comment]
That's  only used for CI isn't it . The defaults are in the binary. The static strategy is always unsafe, that's why I suggested dynamic without subsidy.

**Comment by bh2smith** [comment]
I don't think it's only used for CI, it seems like these values are written at build time. Otherwise I would have run into problems or not having specified these values since they aren't provided as defaults anywhere else.

**Comment by bh2smith** [comment]
That is to say, this file `common.env` is specified as the `env_file` in `/docker-compose.yml`. So anyone following the tutorial, or specific instructions for macOS would run into this problem.

**Comment by bh2smith** [comment]
@e00E is there some way we can remove these default values from `common.env`? Perhaps using a `test.env` that is used for CLI? Or maybe we should have a `docker-compose.test.yml` in the root that is used by CLI and save the existing compose file for the mac users.

**Comment by bh2smith** [comment]
I would like to get some of the ideas aligned here with the input parameters for constructing an `EconomicViabilityStrategy`. 

https://github.com/gnosis/dex-services/blob/ef959111035c978874fc8b03ed66f6e0a6bd6a68/services-core/src/economic_viability.rs#L23-L33

Particularly, we have recently seen a change in the `min_avg_fee_per_order`and `max_gas_price` to being Optional since, they are only used in the case of a Static strategy. However, we don't find that any of the others are Optional even if they don't happen to be used in all possible strategies. This looks as if priority has been given to non-static strategies and I would like to explore the possibility of removing the optional aspect of the two static values (since rust does not allow default values for optional arguments). 

This would not require a change to the method signature as shown above, but only to the main file where options are declared. Doing this would reduce the burden of having to explicitly specify values in our travis configuration, but also come at the risk of not specifying `min_avg_fee_per_order` explicitly, defaulting to zero and paying more gas for a solution submission than would ever be desired.

Perhaps it is best to leave them without default values and optional and allow the compiler complain when they are not provided. I would like to remove all possible dangerous scenarios incurred by default behaviour.

**Comment by e00E** [comment]
subsidy_factor and min_avg_fee_factor are different from static_ because for the former we can pick reasonable defaults while for the latter we cannot. Picking any default for static_ could be unsafe so we force the user to provide them.
I don't see a reason to make the dynamic configuration optional here because we specify their defaults where we declare the command line arguments in main.rs and those defaults are always safe.

**Comment by bh2smith** [comment]
> those defaults are always safe.

Is subsidy factor of 10 always safe?

**Comment by e00E** [comment]
No 10 isn't, I was thinking ahead that we would change the default to 1.

**Comment by bh2smith** [comment]
Right, 1. I had attempted to make it 0, but ran into some issues. I will make that change.
