### ISSUE TITLE
[test non-deterministic]

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#153]
The test e2e-tests-auctions sometimes times out.
```

82.22s$ sh ./test/e2e-tests-auction.sh
MongoDB shell version v4.0.7
connecting to: mongodb://127.0.0.1:27017/dfusion2?gssapiServiceName=mongodb
MongoDB server version: 4.0.10
0
Using network 'development'.
Deposit successful: Slot 1 - Index 0 - Hash 0x105b8eeca0c4f7c035ad1057ae2115eacdbd1c956ea0284c89f6bb7c56cb9104
Using network 'development'.
Deposit successful: Slot 1 - Index 1 - Hash 0x1a3a169be7da1d8fcdf64bb5dca03ee15fe13dfc5b31d6c681ba811f1a384c87
Using network 'development'.
Deposit successful: Slot 1 - Index 2 - Hash 0xe17e3d0a3e3cb07c32145ac0df860dbf7ff1a0e9a20238788a09003fedfc4db8
Using network 'development'.
Deposit successful: Slot 1 - Index 3 - Hash 0x882e6011638ddc54cde9632ad264f79070f721ba49630d328c2f3b4844629339
Using network 'development'.
Deposit successful: Slot 1 - Index 4 - Hash 0xc0e471682b5d2fcd757d5941242dea5a1dd300c1b7a98273722248977d2b7fd2
Using network 'development'.
Deposit successful: Slot 1 - Index 5 - Hash 0x37255d9e4e537066de7c706ac93af4f37f6c9ffa9fbacfc44d5b4039352bafeb
Using network 'development'.
Limit Sell Order successful: Auction 0 - Index 0 - Hash 0x94b5f073930872b0b24d79c4408df094c6cb6721cc8346dcf568179e4a7579bd
Using network 'development'.
Limit Sell Order successful: Auction 0 - Index 1 - Hash 0x4a4310835874fab3dfcf8db28d82830fa2048c39480d96879b49aeda29327433
Using network 'development'.
Limit Sell Order successful: Auction 0 - Index 2 - Hash 0x6af9114cc601525531aff894aed96389106c2bc0997d8993e1a5e72e034b6edc
Using network 'development'.
Limit Sell Order successful: Auction 0 - Index 3 - Hash 0x80e17ce1f17855ee0e194862a46a004a2991f3bc7b2cfa9368090a1d218eec64
Using network 'development'.
Limit Sell Order successful: Auction 0 - Index 4 - Hash 0xfea29890dd89963e6c3c8da24eb867570b006843e20f2ace6766173f99cb6f28
Using network 'development'.
Limit Sell Order successful: Auction 0 - Index 5 - Hash 0x14358f27e523fc4e7ffa2af014acf87222456a066bafa9d039bb325daaf4e361
Before retry #1: sleeping 0.3 seconds
6
280000000000000000000
Using network 'development'.
waited 181 seconds
Before retry #1: sleeping 0.3 seconds
Before retry #2: sleeping 0.6 seconds
Before retry #3: sleeping 1.2 seconds
Before retry #4: sleeping 2.4 seconds
Before retry #5: sleeping 4.8 seconds
Retries exhausted
The command "sh ./test/e2e-tests-auction.sh" exited with 1.
```

**Comment by fleupold** [comment]
Can we verify this is actually a timeout issue? We will have waited almost 10s by the time 5 retries are done. Chances are by that time it will never work. 
Otherwise we should look into why things are taking so long.

**Comment by josojo** [comment]
How can I verify this? 

I got two times failing tests, For one test you see the log in here.

And a simple test reset solved the issue. But yeah, I could try to investigate where the time is lost.

**Comment by fleupold** [comment]
> How can I verify this?

I guess more logging/some profiling to see which part is taking so long. Also running the failing command query 5s after the test has failed (without docker restart) can tell you if it eventually got into the right state.

>And a simple test reset solved the issue

What is a test reset?

> For one test you see the log in here.

I think the docker log is actually more interesting. That one could tell you what was going on.

**Comment by josojo** [comment]
>What is a test reset?
 I meant a test restart.

Okay, I will investigate a little bit more

**Comment by bh2smith** [comment]
Do we know how frequently the driver is pinging the DB for updates? I'd be interested in including more logs in some places. I think it would help me get a better feel for the driver. Maybe we could pair program this together!

**Comment by josojo** [comment]
>Do we know how frequently the driver is pinging the DB for updates?
every 5 seconds and the listener is active every 3 minutes. That means that in the worst case 8 seconds pass before things get transported.

I can not reproduce the issue. All tests in the latest Travis runs pass easily.

**Comment by bh2smith** [comment]
I was experiencing this problem earlier today because the retries that has `grep` at the end don't technically pass until they have successfully found that they are grepping for. In the event that a state hash is not as expected (perhaps due to contract upgrades or some change in the order of operations) these retries will exit without success... In conclusion, this was never really a problem.

**Comment by josojo** [comment]
No, it definitively was a problem.

if a simple travis restart solves the issue, then there was a problem. It's just that I can not reproduce it. Maybe it is because travis is using spot instances, which have some lags or whatever. I don't know But it was for sure an issue.
