### ISSUE TITLE
e2e-tests should not be dependent

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#161]
Currently, the e2e-tests-auction, e2e-tests-standing-order, etc have to be run in a specific order. We should change this by using reverts in ganache-cli.

**Comment by bh2smith** [comment]
So, as I understand, an example of this can be found in the unit tests of the dutchExchange contracts [here](https://github.com/gnosis/dx-contracts/blob/master/test/Tradeflows.spec.js). Specifically watching out for function calls to `makeSnapshot` and `revertSnapshot`. These tests are written in JS so we would likely have to write bash versions of this.
