### ISSUE TITLE
[Rewrite] Switch Listener to Rust

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#164]
This issue captures potential strategies to implement the listener functionality in Rust. While such a change would require work without actually adding a new feature, it would allow us to start sharing code between driver and listener (especially with the potentially more complex account accessing logic (cf #137). This in the long run could make development significantly faster.
Moreover it would reduce the number of languages that we have in our code base (reducing on boarding overhead/requirements) and move to our preferred language.

### Option 1: Pipe django-eth-events into a rust listener

We could spawn a rust process that is opening a port and listening to receive eth events serialized as json. Those events could still come from an django-eth-events instance, in which the only logic would be to forward the events and wait for a success or failure response from the rust code. 
This would require the least effort, however it would still leave a small python codebase and complicate the docker and inter-process communication overhead (event listening and processing could easily run synchronously)

### Option 2: Re-Implement django-eth-events in rust

This would require significant work as we have learned from building `django-eth-events` it is quite hard to build and maintain a reliable eth-events listener that can e.g. deal with reorgs. 
On the other hand we would be able to build it exactly to our needs. 

### Option 3: Use [The Graph](https://thegraph.com/docs/quick-start)

The graph is a tool that allows reacting to Ethereum events with *handlers*. Handlers are defined and implemented on IPFS (using TypeScript). The Graph downloads the handler definition and execution code, which is compiled to WASM and executed at runtime on a graph node instance. 
The output of a handler are a set of database mutations to the underlying subgraph schema (store in Postgres). The Graph takes care of applying and rolling back those changes in case of reorgs. Clients can query the schema using GraphQL.

Advantages:
- Reuse well maintained tool with existing user base
- GraphQL endpoint can make frontend development simpler (no need for a backend)
- Reorgs are abstracted away and don't need to be handled (it remains to be seen if that logic could be used for rollbacks as well)

Disadvantages:
- Significant amount of work required to use only the parts of The Graph we need (e.g. strip away IPFS, TypeScript handling).
- Custom storage optimizations (e.g. how to store/query and update merkle proofs efficiently) might require changes in The Graph and thus potential forking, which could reduce the advantage of using a well maintained library.

**Comment by josojo** [comment]
Good write up.

Another option: (switching to Rust, but postponing the problem)

We could also build a very simple event listener in Rust, which just uses the web3-rust event listen-techniques, but does not do any rollbacks or any fancy stuff.
Then we can start using this instance and build our listener logic in rust and share the logic pieces with the rust driver code.

In the meantime, we watch what other projects are doing (the matter labs, how the graph implementation develops) and only decide later for a proper solution.

(Being able to deal with roll_backs and other fancy stuff might not be our highest priority right now)

**Comment by fleupold** [comment]
> Another option: (switching to Rust, but postponing the problem)

Yes that's an option which would go towards the direction of Option 2. I kind of like that the Graph could also help a lot with the user interface.

**Comment by fleupold** [comment]
Below is a summary in how we believe using The Graph can speed up the development process going forward:

|   | eth-django events|The Graph|
| --- | --- |---|
| New event handler | write Rust & Python processing code (Model + DB interactions + logic) | share Rust handler
| Deal with chain reorg (block-rollback) |dedicated Python implementation for each event| auto-derived from save handler |
|Frontend development|dedicated endpoint for each query/information to be displayed|built-in GraphQL server allows querying data from js|

A potential migration plan from the existing setup could look like this:
1. Include a rust project that reacts to graph events in rust in dex-services (something like https://github.com/fleupold/dfusion-graph)
2. Start implementing existing event handling and unit tests in Rust (writing duplicate archive node in Postgres)
3. Replace driver db interface from MongoDB to Postgres (reading from The Graph archive instead of the django-eth-events archive)
4. Delete old listener/archive node.

We estimate that this will take between 2 and 4 weeks of a single person's time (more granular planning due to actual sprint planning)
