### ISSUE TITLE
[Driver] contract interface: query <-> call

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#181]
In the [contract interface](https://github.com/gnosis/dex-services/blob/master/driver/src/contract.rs), I would suggest to change many contract.call() statements to contract.query()

Reason is that errors are not propagated, if the we calls, only if we use querys. 

See here:
https://github.com/tomusdrw/rust-web3/issues/222

**Comment by nlordell** [comment]
From what I understand from the work I did in `ethcontract-rs` (note that it was with a more recent `web3` version 0.8.0), `Contract::query` doesn't actually put the transaction in the mempool (is that the correct term?) and doesn't actually get mined. It is equivalent to `Contract.function.call()` in web3 JS land which is useful for executing view functions to query contract state.

This means that it can't be used in all cases (for example when you want to mutate the contract state). In that case, I think the correct API to use is `Contract::call_with_confirmation` that will add the transaction to the mempool and then wait for the transaction to be mined and confirmed. This will return a transaction receipt that can be inspected to verify the transaction completed successfully.

**Comment by fleupold** [comment]
I think as soon as we feel `ethcontract-rs` is in a reasonable state, we should adopt it in dex-services. This will make this issue superfluous.

**Comment by fleupold** [comment]
No longer relevant since we are using ethcontract-rs now
