### ISSUE TITLE
[WIP] Create an account entity

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-services#215]
In order to know the orders that are active we have to take into account two facts:
- Every time an user submit a new order batch, invalidates the previous ones for next auctions
- Last assumption is true with the exception of the current batch, where the previous standing orders are still valid

The driver/solver will need to know the standing orders per account. 

## Issue to address
In the current graph implementation, you need to query N-times (N being the number of accounts) and discard the batches you don't need, so you can replicate the pipeline of the python implementation:
* https://github.com/gnosis/dex-services/blob/2143f1f808411528f976c91082509dc4cdc23af3/event_listener/dfusion_db/database_interface.py#L138

## First proposal to iterate with
In order to make it easier for the solver, we could consider de-normalize standing orders, creating a new entity to make sure we can query the active standing orders per user account (only one registry per account).

Every time thegraph indexes an standing order, it also updates this new entity so it always has the latest information.

A first approximation could be something like:
```
type Account @entity {
    id: ID!
    address: String!,
    accountId: Int!
    # ... different PR, but maybe some fields here like current balances
    standingOrder: StandingOdersAccount!
}

type StandingOdersAccount @entity {
    id: ID!
   current: StandingSellOrderBatch,
   previous: StandingSellOrderBatch # might be needed for the solver (for the running auction)
}

type StandingSellOrderBatch @entity {
    id: ID!
    accountId: Int!
    batchIndex: BigInt!
    validFromAuctionId: BigInt!
    orders: [SellOrder!]
}

type SellOrder @entity {
    id: ID!
    accountId: Int!
    buyToken: Int!
    sellToken: Int!
    buyAmount: BigInt!
    sellAmount: BigInt!
    auctionId: BigInt!
    slotIndex: Int!
}
```

If we set  the user address in the `Account` entity as the ID, we can ensure they are unique.
I guess as part of this task is to:
- React to the adition of new standing orders
- Get account for the user + StandingOdersAccount + StandingOders
- Update StandingOdersAccount with the corresponding ids of the standing orders

## Test
- Create e2e test
- unit testing for the new entities conversions

**Comment by fleupold** [comment]
I assume the underlying problem is, that we cannot create a complex group by query [as we are currently doing for MongoDb](https://github.com/gnosis/dex-services/blob/master/driver/src/mongo_db.rs#L130-L158).

I think having an index from account to latest standing order is a good idea.

Another idea, that wouldn't require upfront work could be to issue a single find_one query per account, using a query like this:

```rust
EntityQuery {
  entity_types: "StandingOrder",
  filter: Some(EntityFilter::Equal("account_id", account_id)),
  order_by: "validFromAuctionId",
  order_direction: DESC,
  ...
}
```

Each of this query should give us the most recent standing order batch. Unfortunately, I couldn't find a way to issue many queries in one DB roundtrip, but I'm not sure if performance for 50 reserved accounts is a concern.

**Comment by anxolin** [comment]
I think, the nice thing of mapping the `Account`, is that it totally makes sense to have this entity anyways. 

Building interfaces should be easier. The account in the future can have it's balance for example.
If it's easier to get the orders with that for the driver, it will also for other parties interested on them.

I think it would be a matter also of effort, I think we can live with 50 queries, we don't need to optimize from the beginning. It would be deciding if doing the 50 queries is much much easier, I think it's fine. If not, imo this approach has some additional advantages on top of performance.
