### ISSUE TITLE
Unified Logger

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#263]
The dfusion "service" is currently using two different loggers (`simple_logger` and `graph::log::logger`)
 both instantiated in the following snippet:

https://github.com/gnosis/dex-services/blob/3898d77c7247b457de785196a0437cc11424439e/driver/src/bin/dfusion.rs#L18-L19

Partial reasoning for this is that the graph logger is specific to `the graph` which we only introduced recently.

It would be nice if we used a single logger throughout the project and a _bonus_ if there were timestamps!

**Comment by nlordell** [comment]
This is now possible given #336 was merged.
