### ISSUE TITLE
[Web3] Retry smart contract interactions

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#265]
When running the live demo we can currently see a good number of transient errors, mainly of the form:

```
stablex_1         | 2019-09-26 16:24:08,351 ERROR [stablex] StableXDriver error: Driver Error: [Transport error: Error(IncompleteMessage)]
```

These kind of errors (TransportErrors) should probably simply be retried a few times with exp backoff before escalating.

**Comment by nlordell** [comment]
@fleupold I believe this is now handled with the `RetryableError` when processing a batch. Maybe this can be closed?
