### ISSUE TITLE
Use `serde` to generate JSON serialization/deserialization code.

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#284]
The JSON serialization in `linear_optimization_price_finder.rs` is a good candidate for this.

**Comment by e00E** [comment]
@bh2smith This is exactly the thing I was suggesting to you in our conversation just now.

**Comment by e00E** [comment]
I could probably do this too, if you have something else you would rather work on.

**Comment by bh2smith** [comment]
> I could probably do this too, if you have something else you would rather work on.

That seems reasonable @e00E!
