### ISSUE TITLE
Replace bash e2e tests with rust implementations

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#331]
Our e2e tests are pushing the limits of bash programming and are hard for others to maintain. E.g. using the return value of a call in a next step of the test requires complicated and error prone grep magic.

Long term, we should move these tests to a real programming language (rust or js). We could potentially use the ethcontract-rs crate to make the interactions with the smart contract very simple.

**Comment by bh2smith** [comment]
The following checklist will help track the progress:

- [X] StableX - Rinkeby
- [X] StableX - Ganache
- [] Snapp - Deposit & WIthdraw
- [] Snapp - Standing Orders
- [] Snapp - Auction
