### ISSUE TITLE
Allow to withdraw, even if the token is not enabled

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-services#397]
If we see a balance in the token, we should allow to withdraw it, even in the case the token is not enabled.

Enable token in reality only affects the deposit. So I would enable the deposit button if the there's a balacen, regardless of the state of the "abilitation" of the token.

**Comment by fleupold** [comment]
Is this task supposed to be a part of dex-react? Or what do you need to have changed in the services?

**Comment by anxolin** [comment]
This is from dex-react. Created in the wrong place
