### ISSUE TITLE
[Readme] Update Build Instructions

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#399]
Earlier I was following the readme to build the project but kept failing on driver build for the following reasons:

```
Caused by:
  process didn't exit successfully: `/target/debug/build/driver-e332fd3a4414d929/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../dex-contracts/build/contracts/BatchExchange.json
```

Turns out that one needs to run `yarn run prepack` and also `truffle migrate`from within `dex-contracts` submodule in order for the build to succeed.

**Comment by fleupold** [comment]
addressed by #410
