### ISSUE TITLE
Update Solution Struct

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#412]
The current solution struct 

https://github.com/gnosis/dex-services/blob/2a442f847dfe716b83a5784528910a0ad6abb60d/dfusion_rust_core/src/models/solution.rs#L8-L13

Has a vector of prices, which is unnecessary if we know beforehand that some tokenIds will have a price of zero (i.e. those tokens which are not traded). Thus, it would be more reasonable to have the 
 `prices` attribute as a `HashMap<u16, u128>`. We may also want to include an attribute `max_non_zero_token`

We may also want to consider (simultaneously) adapting the `Fee` struct since the fee token is always 0.

https://github.com/gnosis/dex-services/blob/2a442f847dfe716b83a5784528910a0ad6abb60d/driver/src/price_finding/price_finder_interface.rs#L6-L10

**Comment by fleupold** [comment]
I like it, but would prefer to leave the fee token flexible in that it could be any token (unless there is a technical reason not to).
