### ISSUE TITLE
Do not submit solution in last minute of the batch

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#416]
Otherwise we are getting an error saying `Solutions are no longer accepted for this batch`. This is however not an error but expected behavior

Pointer to where we check objective value and submit solution: https://github.com/gnosis/dex-services/blob/master/driver/src/driver/stablex_driver.rs#L44. Both steps can be omitted if we are in the last minute of a batch.

**Comment by nlordell** [comment]
Maybe we can clean up the logging when there is an error checking the objective value? I feel like there should be warnings when checking the objective value fails because the submission window was missed.

**Comment by fleupold** [comment]
I think any failure to check the objective value should be logged. The only one that is not technically an "error" is if there was a better solution submitted in the meantime. But even missing the time window means that our solver is not parametrised correctly.

**Comment by bh2smith** [comment]
We are currently indirectly checking this my making a "call" to `submit_solution` which would fail if it were the last minute. We could improve this my making a call to `accepting_solutions` and logging the results better

https://github.com/gnosis/dex-services/blob/0cf8d946aafbf77c6d0276e8539bfa06123344bf/driver/src/driver/stablex_driver.rs#L56-L60

**Comment by fleupold** [comment]
With the update to the more recent ethcontract-rs version we should be getting the revert messages as error message, which will tell us if "solutions are no longer accepted"
