### ISSUE TITLE
Allow batched querying of order book

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#433]
Our [rinkeby deployment](https://rinkeby.etherscan.io/address/0x66b41d8177d6f7cd7316d9a06ecff5302249ee7c) of the contract seems to have exceeded the maximum capacity of order that we can query with a single view function call (cf. invoking the get_auction_elements script results in `Error: Returned values aren't valid, did it run Out of Gas?` even when running it with an extremely high gas limit).

We might locally be able to work around this issue by increasing the gas limit for view function calls to something very large, but in the long run we should make use of the batched query API that the smart contracts provide.

Unfortunately, this requires a new deployment of the smart contracts which isn't scheduled until in two weeks.

**Comment by e00E** [comment]
We will add another implementation of `OrderBookReading` that uses `getEncodedUsersPaginated` (which should be called `getEncodedOrdersPaginated`). Then we can choose between the paginated and non paginated versions.

**Comment by e00E** [comment]
How should the configuration work?  There is a choice whether the paginated api should be used at all and then what the page size should be.
Did you already have something in mind for this @fleupold ?

Imo there is no reason to not use the paginated api so we might as well always use it.

**Comment by fleupold** [comment]
> Imo there is no reason to not use the paginated api so we might as well always use it.

Yes that sounds reasonable. Let's use an env variable to specify the page size.

**Comment by fleupold** [comment]
@e00E can you please use a larger page size on the staging deployments (e.g. 1000). There we have full nodes that run with "unlimited" (u64::max) gas limit.
