### ISSUE TITLE
Two solver setup

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#446]
In order to increase the robustness of our solver system, we might want to start two solvers for the same instance. One solver would try to find solutions with the LP-optimization procedure and one with the NLP-optimization procedure.

While one driver could start also two processes calculating the solutions to the different optimization problems, having two completely separate drivers allows us to test the scenarios with competing solutions.

The only downside might be that running two different drivers will incur more cost in terms of gas costs and server costs.

This task is closely related to #435
Additional to #435, we should make sure that we have auto deployments for more than one solver.

**Comment by fleupold** [comment]
Let's tackle the auto deployments as part of #435 and consider this a duplicate.
