### ISSUE TITLE
Remove 0 prices from PriceMap

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#450]
@bh2smith suggested this in https://github.com/gnosis/dex-services/pull/443#discussion_r367938770 :

> Actually I was hoping we could actually leave zero prices out of the price map and adjust the logic in a couple other places to infer zero as a default when the prices are not included.
We would then no longer need the "TokenNotFound" error in objective function evaluation.

**Comment by e00E** [comment]
I believe this issue is no longer valid.

**Comment by bh2smith** [comment]
Thanks for keeping on top of this @e00E, could you please elaborate why this is no longer valid?

**Comment by e00E** [comment]
Because when we changed the json format between dex-services and the solver we solved this issue (i think). There no longer is a TokenNotFound error.

**Comment by bh2smith** [comment]
Yes, this was one point of the purpose for doing this, but there was also the fact that our trivial Solutions look like this:

```
Solution { prices: {9: 0, 5: 0, 7: 0, 4: 0, 3: 0, 18: 0, 0: 1000000000000000000, 16: 0, 10: 0, 2: 0, 6: 0, 19: 0, 1: 0, 17: 0, 15: 0, 11: 0, 14: 0, 13: 0, 8: 0}, executed_orders: [] }
```

Eventually there will be too many tokens and this will look even sillier than it already does. 

The purpose of this issue is to remove the zeros from this mapping so that trivial solutions are nice and compact like this:

```
Solution { prices: {0: 1000000000000000000}, executed_orders: [] }
```

**Comment by bh2smith** [comment]
It turns out that this is actually more related to a feature request with the solver project. That is, we should request that the prices with `null` values not be included in the results dict.

https://github.com/gnosis/dex-solver/issues/242
