### ISSUE TITLE
[E2E] Incorrect Expected Balance

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#451]
https://github.com/gnosis/dex-services/blob/8f7aebf66f790726349d1a7736953a1e263daf4b/test/e2e-tests-stablex-ganache.sh#L26-L27

I ran this ganache test locally and failed on the final step:

```
➜  dex-services git:(e2e_snapp_refactor) ./test/e2e-tests-stablex-ganache.sh
✔ Setup 
✔ Make sure we have enough balances for the trades 
✔ Place 2 orders in current auction 
✔ Advance time to close auction 
✔ Request withdraw 
✔ Advance time to finalize withdraw 
❌ Claim withdraw 
Command: npx truffle exec scripts/stablex/claim_withdraw.js --accountId=0 --tokenId=1 | grep "Success! Balance of token 1 before claim: 3000000000000000000000, after claim: 3999000000000000000000"
```

It appears the claim was successful, but the balance was unaffected.
I have also been able to run the claim script multiple times with apparent success... which seems odd.

**Comment by fleupold** [comment]
If you run the steps manually what is the output of the claim withdraw script?

**Comment by bh2smith** [comment]
Actually, this error is probably just the result of the fact that the `driver` and `listener` containers aren't running. Closing this issue.
