### ISSUE TITLE
Driver out of sync with batches.

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#475]
As the batches are now more complicated and the solver takes the whole 3 minutes, I suspect we might have to rework how the driver is trying to solve things.

Specifically, right now we can get into a situation where the driver can run the solver multiple times per batch, and since the solver runs for about 3 minutes, the second solver will miss the solution deadline and cause solver to start late for the next batch:

Here are the logs for one such example: https://logs.gnosisdev.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-01-29T19:45:50.000Z',mode:absolute,to:'2020-01-29T22:59:59.999Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'7ea8a550-5471-11e9-98b4-3b011d27ba56',key:kubernetes.container_name,negate:!f,params:(query:dfusion-mainnet-master,type:phrase),type:phrase,value:dfusion-mainnet-master),query:(match:(kubernetes.container_name:(query:dfusion-mainnet-master,type:phrase))))),index:'7ea8a550-5471-11e9-98b4-3b011d27ba56',interval:auto,query:(language:lucene,query:'%22driver::%22'),sort:!('@timestamp',asc))

Here the driver:
- **`19:45:50.982`** checks the batch ID
- **`19:45:51.159`** generates the solver input and starts the solver
- **`19:48:53.091`** solver finishes with a solution
- **`19:48:53.098`** solution is checked
- **`19:48:53.178`** check fails (because of a subtraction underflow - might be related to the negative objective value issues that we are seeing)
- **`19:48:58.182`** batch ID is queried for the **same batch**
- **`19:48:58.345`** the solver is started again for the **same batch**
- **`19:52:00.436`** solver finishes late, as it was started late
- **`19:52:05.743`** solver is started for the next batch, but 2 minutes late
- **`19:55:08.060`** solver finishes within the 3 minute window, but is late for the batch because it was started late.

I hope this illustrates the problem!

**Comment by fleupold** [comment]
I guess #421 should be extended to also not retry smart contract failures? It would help if we can inspect the error and make sure we can retry intermittent ones and not retry permanent ones like a subtraction overflow.

**Comment by nlordell** [comment]
Sounds like a good solution to me!

**Comment by nlordell** [comment]
Would it also be useful to check at the start of run loop how much time is left in the batch, and if it is under some threshold skip that batch?

**Comment by josojo** [comment]
>I guess #421 should be extended to also not retry smart contract failures?

Yeah, we should do that for sure, yes.

> Would it also be useful to check at the start of run loop how much time is left in the batch, and if it is under some threshold skip that batch?

We could additionally also pass over a parameter, for how long solver should run. The solver could also try to find a solution within a shorter time period in these situations.

**Comment by fleupold** [comment]
GIven that #477 is merged can we close this?

**Comment by fleupold** [comment]
We do collect metrics on how long it takes until we kickoff the driver. While we don't use this data yet, it will help us assess if we need to become smarter about how long to run the solver. I think for now a fixed time is sufficient.
