### ISSUE TITLE
[Ops] Keep instances around for 7 days

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#478]
At the moment we can recover the auction instances from the AWS machines until the next restart. A restart happens on every master build, thus instances tend to only be around for a few hours. We should keep them around at least for 7 days on a shared volume similar to how we are keeping the instance of the kraken test runs around.

In the meantime the full instances can also be found in Kibana, which have an even longer retention.

**Comment by josojo** [comment]
Why is this necessary? Which data can not be extracted from Kibana?
Is this just for convenience?

**Comment by fleupold** [comment]
Large instances are a bit annoying to recover from kibana. It requires stitching together multiple log statements (as Kibana has a max log size fo 16kB). This will make it very easu (one line command) to get the order book for a certain instance we want to inspect.
