### ISSUE TITLE
Implement external price feed

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#507]
The logic implemented in https://github.com/gnosis/dex-solver/pull/121 breaks the interface between the services and the solver. The solver should not rely on external information that it has to fetch e.g. via network. It should work just based on the input json (cf. [comment](https://github.com/gnosis/dex-solver/pull/121#issuecomment-582513764))

This task captures to implement the centralized price oracle fetching logic in the services.

**Comment by twalth3r** [comment]
Format-wise, we thought it would be most concise to extend the list of tokens in the JSON to a dictionary that can contain any additional information for each token.

I.e., currently, we have
```
tokens = [
    'T0000',
    'T0001',
    'T0002',
    ... ]
```

Our suggestion would instead look like
```
tokens = {
    'T0000': {
        'decimals': 18,
        'externalPrice': 1.0,
        'alias': 'OWL'    <--- example for optional info
    },
    'T0001': {
        'decimals': 18,
        'externalPrice': 250.0
    },
    'T0002': {
        'decimals': 6,
        'externalPrice': 0.9997
    },
    ... }
```

The external price can be given both as human-readable float (together with the number of decimals) as well as already converted big-int representations.

**Comment by josojo** [comment]
@twalth3r @marcovc 

What should we do, if we don't have any data for a token? Would the following work:
```
tokens = {
    'T0000': {
        'decimals': 18,
        'externalPrice': 1.0,
        'alias': 'OWL'    <--- example for optional info
    },
    'T0001': null,
    'T0002': {
        'decimals': 6,
        'externalPrice': 0.9997
    },
    ... }
```
if we have no data for T0001 ?

**Comment by twalth3r** [comment]
@josojo - yes, that works! We will probably be storing it as empty dict  (`'T0001': {}`) internally, so that would be even better, but not sure if JSON allows this!?

**Comment by fleupold** [comment]
Should `previousPrice` then go in the same dictionary instead of being a top level field on the instance?

**Comment by twalth3r** [comment]
`previousPrice` can even be left out for now. If we eventually get previous dfusion prices, these should definitely go in the same dictionary!
