### ISSUE TITLE
Late start to the batch waiting for a block to be mined at the start of a batch

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#518]
Because of how time works on the EVM, only once a block has been mined and synced by the node after the start of a batch does the `getCurrentBatchId` query return the next batch ID. This cause the batch calculation to start late. While this is kind of unavoidable here are some ideas on how to solve it:
- 15 seconds after the start of the batch, assume that no more blocks that were mined before the start of the batch will arrive
- Have competing drivers that use different strategies for synchronizing batches (one that starts at specific time intervals and one that uses the polling method used now).

**Comment by e00E** [comment]
Closing because we have the SystemTime based batch solving now.
