### ISSUE TITLE
Detect overlapping order book

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#536]
Suggested by @josojo 

While clearing overlapping orders is a non trivial task (due to logic of connecting and moving fees into the fee token), it should be relatively straight-forward to detect when order books are overlapping on a certain token pair. 

If we still receive a trivial solution in those cases, we could log a warning (increment a prometheus counter) and thus raise awareness. 
This would allow fetching and analysing the order book by hand.

**Comment by josojo** [comment]
We discussed this in the solver -meeting today.

And actually, we think it is better to build an 'instant greedy solver", which first calculates a base-line solution based on overlapping orders and then starts the real solver to find a better solution.
See here:
https://github.com/gnosis/dex-solver/issues/144

Lets discuss on Monday
