### ISSUE TITLE
Add timeouts for all network communication

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#542]
When the ethereum node is slow we can block indefinitely on calls to it. Instead we should configure a timeout so that we can handle this as an error.

**Comment by fleupold** [comment]
Since HTTP transport doesn't seem to allow a global timeout, the easiest way would probably to build a wrapper transport similar to how we have built the LoggingTransport.

It would also be great if we can collect metrics about round trip times into prometheus to be able to alert based on them.
