### ISSUE TITLE
Proper setup for emergencyDriver deployments

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#545]
In the last incident review meeting, we concluded that in an emergency situation it would be helpful to be able to deploy old docker images of the driver.

Unfortunately, this is not as trivial as we thought, as we also want to have proper logging for these emergency instances and hence new volumes must be mounted etc.

Task
-> Coordinate with deops for the best solution
-> document the emergency driver start

**Comment by fleupold** [comment]
@josojo can you please also update the Oncall instructions https://gitlab.gnosisdev.com/devops/gnosis-staging/blob/23bae0d9f7c7080839794bb6aea907c5a830ec8e/deployments/development/dfusion/ONCALL.md#L121
