### ISSUE TITLE
Pass OrderID in json to the solver

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#546]
For debugging and particularly to blacklist "bad" orders, it would help a lot to include the orderId in the instance json that is passed on to the solver.

Moreover, I'd suggest to parse the resulting solution data based on the order IDs (at the moment we rely on the index in the result array). This would allow us on the solver side to only include orders in the result set that have a non-zero execution amount which would make analysing auction results much easier.

**Comment by e00E** [comment]
Here is what I think we should do:

1. When communicating with the solver identify orders by their `accountId` and `orderId` instead of relying on the index in the list of orders. To do this we add the `order_id` field (`account_id` already exits) to the rust code.
2. We update the solver to use the new format which allows it to return the orders in the solution in any order and omit orders that were not touched.
3. We update the rust code to handle the new solver output format and bump the version of the solver at the same time so that we use the version that produces the new output.

For now we can only do step 1, then we need to synchronize with the solver being updated.

**Comment by e00E** [comment]
Maybe someone from the solver could comment whether this makes sense. Not sure who I should ping. @twalth3r

**Comment by twalth3r** [comment]
Generally, I agree that it would help us to be able to identify orders by ID. Currently, first thing the solver does is to give every order an ID (basically its index in the list with leading zeroes, e.g., '007'), and then stores them as dict for the rest of the execution. For this, I'd prefer an ID that is unique in itself over having a combination of (orderID, accountID).

An easy suggestion would be that you just add a field `orderID` as you proposed, which we don't touch but carry throughout our code; while we stick to our current internal ID.

Would that work for everyone?

**Comment by e00E** [comment]
As long as the order id stays there in the solution it doesn't matter what happens internally and it should still be possible to omit orders that have zero execution amount in the solution.

**Comment by fleupold** [comment]
My original idea was to restart populating the globally unique ID on the services side (as was the case before) and make it so that we can derive the per user ID from that value. However, the proposed solution here seems cleaner.
If @twalth3r is on board with passing this value through to the solution file, this seems like a good way to go.

**Comment by twalth3r** [comment]
>If @twalth3r is on board with passing this value through to the solution file, this seems like a good way to go.

I'd be fine with that! It would just need to be called `orderID` (or whatever) and not just `ID` (which we use internally). Do we need to have this passing-through logic ready when this PR is merged, or are you not yet relying on it?

**Comment by e00E** [comment]
As long as the solver won't have problems with an unknown field its not urgent. All  the above PR does is add the `orderId` field to the json but it does not expect the solution from the solver to change at all.

**Comment by twalth3r** [comment]
@e00E - I just tried and it seems to even work out-of-the-box without any changes required on our side.

**Comment by twalth3r** [comment]
Just noticed that there is a little inconsistency in the spelling of the IDs:
* `accountID` with capital `D`
* `orderId` with lowercase `d`

I personally slightly prefer the first variant, but have no strong feelings. We can also keep it as it is :man_shrugging:

**Comment by fleupold** [comment]
The choice seems to differ from language to language [[1](https://softwareengineering.stackexchange.com/questions/186277/should-the-variable-be-named-id-or-id)], but I agree we should be consistent.

The default CamelCase deserialisation would name it `Id` (we have a custom override for accountId) that we introduced for accountID, but also no strong feelings.

**Comment by twalth3r** [comment]
If I can make a wish for being consistent, then I'd like it to be `orderID` - we're using `ID` and `accountID` everywhere (also all the old JSON instances of course).

**Comment by fleupold** [comment]
Sounds good to me. We can probably go ahead assuming the field will be renamed to orderID and fix it in the PR that starts depending on the new solver version.
