### ISSUE TITLE
Grafana logging keeps processing times from previous batch

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#549]
Discussion on https://github.com/gnosis/dex-services/pull/537#discussion_r380031943

@e00E noted

> I noticed in grafana for solution submission it keeps using the previous value when we don't actually submit a solution. Maybe it would be clearer to reset it to 0 at the start and for every batch where don't really reach the step. Or maybe not, just throwing it out there.

@fleupold answered

> Yes, I noticed that too. My concern about clearing is when would we do that? If we clear to early we might not get a sample at the actual value and thus miss the measurement. After all maybe a gauge is not the right metric type here?

@e00E replied

> The sampling problem we already have because technically the next batch could be solved so quickly that the old value cannot be measured even though this is unlikely.
This goes back to the discussion when the metrics were introduced that having these processing times as gauges does not fit the prometheus model. A histogram is more appropriate but then you cannot get the exact processing times and you cannot show just the most recent value.
What we really want is to log the processing times of each stage whenever the stage completes. This could go into a file or sql database table. Then that table contains exactly the information we want. I don't think this accomplishable with Prometheus. Maybe we can log into kibana or some postgres or sql server and have Grafana plot that.

**Comment by e00E** [comment]
This is no longer the case.
