### ISSUE TITLE
Emergency backup for price data

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#555]
As price feed might not be 100% reliable or simply do not offer all needed data, there should be the option to pass additional token information + their prices to the driver and solver via a new env variable.

The format for token information should be aligned with https://github.com/gnosis/dex-services/issues/507

**Comment by nlordell** [comment]
Did you mean to assign this to me? I thought this was being done with #556

**Comment by josojo** [comment]
No, I did not mean to assign this to you sorry.
I unassigned you immediately.

*Alexander Herrmann*
Mechanism Designer at Gnosis <https://twitter.com/Herrmann_A_>
<https://www.linkedin.com/in/alexander-herrmann-a98573a5/>
<https://t.me/alexx_herrmann>
------------------------------
<https://gnosis.io/>
*Gnosis Service GmbHwww.gnosis.io <https://www.gnosis.io/>*
Amtsgericht Charlottenburg | HRB 188071 B
Geschäftsführer: Dr. Friederike Ernst, Stefan George & Martin Köppelmann
