### ISSUE TITLE
Simple Solver

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#58]
At minimum, this simple solver should find at least 1 direct match (i.e. any non-trivial solution to the orders provided). 

This will be used for the purpose of testing (with small examples).

one suggested solution here is to loop over each token pair and find two orders `i for j` and `j for i` with prices that agree. Then set the median of these limit prices as the price between `i` and `j` and continue for other pairs... or stop at this point.

**Comment by fleupold** [comment]
A slightly more sophisticated version, could keep track of a price range for previous matches. As it finds another match for the same trading pair, it checks if their supported price range intersects with the one that was previously found.

But let's start simple and see how far we get.
