### ISSUE TITLE
Retrieve price information at the end of the previous batch

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#583]
The idea is to retrieve the price information at the end of the previous batch, or at the beginning of the current batch while we are waiting for a block to be mined after the batch start so the batch ID increments.

This is to take advantage of the down time in order to retrieve the price information without having take up some of the solver time.

**Comment by e00E** [comment]
Closed because we do price estimation in a background thead. It isn't per se updated always at the end of a batch but in 5 minute intervals which seems fine. If we want to we could implement manual updating at the end of batch too.
