### ISSUE TITLE
Benign error not recognized as such

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#602]
We got the following error in the prod env:
https://gnosisinc.slack.com/archives/CUD4MUCUF/p1583164918001300

But it should have been a benign error.

**Comment by fleupold** [comment]
> [DFUSION] threw an error
ERROR (pod: dfusion-mainnet-fallback-solver-c9b9cfd88-tr52n): 
Mar 02 16:01:27.037 DEBG [driver::transport] [id:2052] received response: '{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Reverted 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003b4e6577206f626a65637469766520646f65736e27742073756666696369656e746c7920696d70726f76652063757272656e7420736f6c7574696f6e0000000000"},"id":2052}

You can see that severity is of type DEBG. I assume the following query has to be applied to prod as well: https://gitlab.gnosisdev.com/devops/gnosis-staging/blob/24e113e87cf3302fedac12e7e06310af8184e598/deployments/cluster-tools/logs/elastalert/rules/dfusion/dfusion-error.yaml#L24

Not that we check for ERRO in the log (which this message doesn't have)

**Comment by josojo** [comment]
Denis fixed this already, but gave us the following hint:
```
Ah ok, it's a small difference in the prod alert configuration that was causing this, I can change it.
But I think it might be better to have logs separated by stderr and stdout too?
``

**Comment by fleupold** [comment]
Good to close then?
