### ISSUE TITLE
Wrong error when transaction reverts with ganache

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#605]
See https://github.com/gnosis/ethcontract-rs/issues/216

While playing with the ganache e2e test I tried got a transaction to fail when depositing the tokens into the accounts at the beginning of the test. In this case this failed because not enough of the token had been minted (I think). 

The bug is that the returned rust error was wrong
```
MethodError { signature: "deposit(address,uint256)", inner: Web3(InvalidResponse("Error(\"data did not match any variant of untagged enum Response\", line: 0, column: 0)")) }
```

@nlordell mentions in the linked issue that this is a bug in our `Transport` implementation.

**Comment by nlordell** [comment]
@e00E Do you happen to have the JSON RPC response that you got from Ganache when the transaction reverted? I would like to use it to add a unit test.

**Comment by e00E** [comment]
Unfortunately no. The way I got it back then was to copy paste the logging transport into the e2e test and then triggering the failure by depositing more than has been minted.

**Comment by fleupold** [comment]
Will close this, since it seems to be something that should be handled in ethcontracts rather than here.

**Comment by nlordell** [comment]
@fleupold 
> Will close this, since it seems to be something that should be handled in ethcontracts rather than here.

I think, this particular case needs to be handled here by our transport implementation. Alternatively it can be handled in the `jsonrpc-core` crate, but I don't know if it would be accepted there as the Ganache behaviour goes against the JSON RPC specification.
