### ISSUE TITLE
Improve Docker Configuration

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#61]
- Better use of _onion principle_ 
- Remove images and run natively on Travis
- Don't run SQL interface when running tests.

Task to be completed as a team pair programming event mid April.

**Comment by fleupold** [comment]
Spent 2 day so far. Build time wen from close to 20 minutes to 12. 2 more minutes can likely be saved by using base images that have all necessart apt-get packages already installed.

**Comment by bh2smith** [comment]
Can we close this?

**Comment by fleupold** [comment]
I think it's worth doing the remaining optimizations (optimizing base images) if we get the chance.
