### ISSUE TITLE
k8s monitoring system creates false errors

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#614]
Over the weekend, we have seen several warning of missed auctions like these ones:
https://gitlab.gnosisdev.com/devops/gnosis-staging/issues/34

But I can not find any errors in the logs. Everything looks normal and the solver finds a trivial solution in all cases.

We should make sure that these false warnings are turned off.

I can not find where we configure the k8s monitoring system. Can anyone help me out?

**Comment by josojo** [comment]
@e00E noted that these issues are exactly 12h apart. So it should be something about the setup of k8s monitoring

**Comment by luarx** [comment]
I think that it is because we are not using the right expression in our k8s monitoring system to fire alerts (as it is a **accumulative** metric we need to calculate the difference from now and X minutes before)

Will change it and let's see!
