### ISSUE TITLE
Use system time to start batch processing

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#616]
We are currently waiting for the first block to be mined with a timestamp in a batchID `t` before we start solving `t-1`. This leads to unpredictable start times and can be inefficient (sometimes a block isn't mined until one minute into the batch).

A better approach could be to use the system clock and wait for a certain amount of time (e.g. 30 seconds but could be configurable) before starting to process the batch. Even if there is no block mined within 30 seconds of the 5 minute cutoff, any future block is likely going to have timestamp on batch `t` and thus not affect the previous batch `t-1` in terms of orders (making it safe to start processing).

An even more optimal solution could use a hybrid, where we wait at most 30s but start if we see a block with the right timestamp before (yet this adds significant extra complexity and might not be worth it).

**Comment by josojo** [comment]
I am unsure whether this is really the right step: ( sorry for starting the discussion so late, I must have overlooked it)

There are two risk with the new appraoch:
- the timestamp of the new block still falls into the old batch.
Cr[ here](https://ethereum.stackexchange.com/questions/5924/how-do-ethereum-mining-nodes-maintain-a-time-consistent-with-the-network):
>: For clarity, in Ethereum, the only rule about timestamps is that the timestamp must be greater than the previous timestamp. There is no other rule: old docs such as the white paper and wiki may mention 15 minutes (900 seconds),
- we are getting a reorg

In both cases, we would likely solve the batch with the wrong information. While it is scenario is quite unlikely, I would weigh reliability and correctness higher than time gains of 15s on average.

If we start optimistically, as suggested by Felix, I think that we need to have checks in place that alarm us, in case the blockchain reorgs or generates incorrect timestamps.

**Comment by fleupold** [comment]
Reorgs can also affect us in the old setup. Only because a block is mined with a new timestamp, it doesn't mean there exists an uncle chain with another block still inside the old batch which will eventually become part of the longer chain.

I think it really depends on how long we wait. Our current assumption is that if by 30s into the new batch no block was mined, it's very unlikely someone will mine a block with a timestamp more than 30s in the past (even if the protocol allows it). In a more conservative solver we can wait for 1 minute.

We do want to build the orderbook in an incremental way which will allow streaming new orders and cancellations into the driver. The driver can then decide if they want to restart computation in case of a new order/cancellation.

Theoretically we could also build multiple implementation of our "scheduler" component. One that's based on system time and one that is based on blockchain time. This might also help us improve the long running ganache e2e test we are having at the moment.

**Comment by josojo** [comment]
>We do want to build the orderbook in an incremental way which will allow streaming new orders and cancellations into the driver. The driver can then decide if they want to restart computation in case of a new order/cancellation.

This is the right solution in the long run. Sure!

>Reorgs can also affect us in the old setup. Only because a block is mined with a new timestamp, it doesn't mean there exists an uncle chain with another block still inside the old batch which will eventually become part of the longer chain.

But the likelihood is a little bit more in our favor with the old setup, isn't it?

Anyways, if you guys wanna go for, let's do it. I think the repercussion is just a slight shift in the probability of exceptional events.
