### ISSUE TITLE
Should CI fail on warnings?

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#630]
https://github.com/gnosis/dex-services/pull/628 changed the way logging works. We log only errors to stderr, and only less severe messages to stdout. This allows us to check for errors in the e2e test by checking whether stderr is empty.

It might be useful to assert that in addition to errors also no warnings were observed. On the other hand warnings can be benign like the kraken or dexag api being down.

We could implement this by using two independent log filters for stdout and stderr and then configure CI to include warnings in stderr. This way we can filter warnings by module so only some module warnings turn into errors.

**Comment by fleupold** [comment]
My 2c is that warning should not block CI especially if our way to work around them would be to ignore certain modules. 

Maybe it makes sense to still "alert" the on-call (e.g. by sending an email with the warning that was produced)? Or we could maintain a list of regexs that are considered "benign warnings" but I'm not sure how scalable this is long term.

**Comment by nlordell** [comment]
I would be inclined to agree as well, but the warning did catch a bug in one of our PRs (only because the warning message included the string `"error"` in it). That was my main argument for also having CI fail on warnings.

**Comment by fleupold** [comment]
We discussed to continue not erroring on warnings.
