### ISSUE TITLE
Verifying Objective Value can fail when last mined block still in previous batch

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#663]
We ran into this error today: https://logs.gnosisdev.com/goto/ac3395f35503815eebfcaeccafe15ffb

> ERROR (pod: dfusion-mainnet-fallback-solver-5594664f47-st9xt): 
Mar 26 16:45:41.739 ERRO [driver::driver::scheduler::system] StableXDriver unretryable error: method 'submitSolution(uint32,uint256,address[],uint16[],uint128[],uint128[],uint16[]):(uint256)' failure: contract call reverted with message: Some("Solutions are no longer accepted for this batch")

The error message is somewhat misleading, because solutions were actually **not yet** accepted for this batch. 

### Problem

There was a 3 minute gap between block [9748132](https://etherscan.io/block/9748132) and [9748133](https://etherscan.io/block/9748133) (first mined at 04:43, second at 04:46). 

When we validated the solution at 04:45:41 the most recent block on the node we were querying had a timestamp from the previous batch (5284135) and therefore failed the verification process for batch ID 5284136 (as it believed it was not yet accepting solutions for this batch).

### Potential Solutions:
1) We could wait until a block is mined in the new batch before running the validation
2) Maybe there is some node configuration that allows pretending a block is mined at the time of the RPC call.

**Comment by fleupold** [comment]
Another example: https://logs.gnosisdev.com/goto/49bd4ae1dfff3062a11171a2a5c0ea40

Block [9750080](https://etherscan.io/block/9750080) and [9750081](https://etherscan.io/block/9750081)

**Comment by nlordell** [comment]
I like both solutions. The only other one I can think of requires a contract change.

**Comment by josojo** [comment]
> Maybe there is some node configuration that allows pretending a block is mined at the time of the RPC call.

I would prefer this option, as it allows us to validate our solution and send the transaction out before the next block is mined. Hence our solution would get mined one block earlier compared to the other proposal.

**Comment by fleupold** [comment]
Agree, this can also reduce the number of failures we run into, as we can check if there is already a better solution in the mem-pool.

However, it might not fully fix the problem, as even the pending block's timestamp seems to be slightly out of sync. I executred the following command a few times:

> date && curl -s -H "Content-type:application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending", true],"id":1}' https://node.mainnet.gnosisdev.com | jq '.result.timestamp, .result.transactions[0].blockNumber'

and then compared the returned timestamp with my local time.

But it's a good start and if it doesn't fix the problem we can still implement a more aggressive waiting strategy.

**Comment by fleupold** [comment]
Prod had a bunch of "Solutions are no longer accepted for this batch" errors last night, whereas staging (where the change is already applied) did not.

We did however run into another similar issue (on both prod & staging) that I captured in #666

**Comment by e00E** [comment]
The solution truly was invalid because the block had not been mined but it is likely that in the block that includes the solution transaction it is going to be valid.

Potential Solution 3: Reimplement solution verification in rust.

That has the drawback that it relies on the local orderbook being correct and that we're reimplementing the smart contract in rust.

I don't think it is possible to pretend the block is mined. The closest thing I see is https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call where you can set the block to pending.

**Comment by fleupold** [comment]
> Potential Solution 3: Reimplement solution verification in rust.

That's a good idea, we have implemented using the "pending" block for now. If that doesn't help we should do that.

**Comment by fleupold** [comment]
This seems to no longer be happening. Closing for now.
