### ISSUE TITLE
Delayed solution submission for the open source solver.

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#664]
The solver team would like to run the open-solver soon. But since this solver is much quicker than the other solvers, the open solver would always be the frist submitting a solution. Since we are expecting the other solvers to find a better solution, the first "open-solver"-solution is very likely to be reverted.

We want to avoid this expensive reversion of the solution. Hence, the open solver should always just submit a solution, if no other solution has been submitted until 3:30 minutes into the batch. Hopefully, this saves us some costs. 

Maybe someone else has also another better proposal for delayed solution submission.

**Comment by nlordell** [comment]
I think we can cheat for now by setting the solver start time for something really high like 3:20. That way the solver will only be run near the end of the batch.

The env var is `TARGET_START_SOLVE_TIME`.

**Comment by josojo** [comment]
This suggestion is great. Closing
