### ISSUE TITLE
Wrong Orderbook when last mined block still in previous batch

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#666]
Somewhat related to #663 

We start our processing 30s into the batch. The first thing we do is query the "current" orderbook based on the latest block. If the latest block still has a timestamp that lies in the previous batch, we therefore query the orderbook from the batch before the one we are meaning to solve.

This can lead to failures if e.g. orders were cancelled or proceeds were withdrawn.

### Example

This happened in staging/prod a few times last night. Here is the timeline of on concrete example:

- *12:36:55 AM* [Withdraw Request](https://etherscan.io/tx/0x55f5a9c6bbc72b48f4182cf90930eaeb5c8c73aeee52ed5f726017862fbb8659)
- *12:39:58 AM* [Last Block](https://etherscan.io/block/9756781) before orderbook fetching started
- *12:40:30 AM* Orderbook fetching started

In the [instance data](https://gnosis-dev-dfusion.s3.amazonaws.com/data/mainnet/standard-solver/instances/2020-03-28/instance_5284519_2020-03-28T00%3A40%3A40.492950889%2B00%3A00.json) we can see that we assumed an available balance of 4460 DAI for account 0xb210d9afde9cda1b8af0d260ad8602f5134f6cac although this amount was already requested for withdraw for the batch we were trying to solve

### Solutions

- Short term, I'm adjusting the fallback solver to start processing later and thus make it more unlikely we are mining on an old block (https://gitlab.gnosisdev.com/devops/gnosis-staging/merge_requests/202)
- Midterm we should probably do the same fix as #663 and fetch the orderbook based on the pending block to allow having a more recent timestamp
- A more longterm fix would be that instead of fetching "the current" orderbook based on the blocktime of the node, we deliberately fetch the orderbook for a given target batch. The BatchExchangeViewer wrapper contract [supports such calls](https://github.com/gnosis/dex-contracts/blob/master/contracts/BatchExchangeViewer.sol#L94-L97). However we should discuss if we are moving towards an incremental orderbook soon enough that this work would not be worth the effort.

**Comment by fleupold** [comment]
I'm not sure it is a coincedence that this task ended up having the [Number of the Beast](https://en.wikipedia.org/wiki/Number_of_the_Beast)

**Comment by josojo** [comment]
Excellent write up:

>Midterm we should probably do the same fix as #663 and fetch the orderbook based on the pending block to allow having a more recent timestamp

Agreed that would be the best fix short-term. We could have thought about this during reviewing the PR for fixing 663...

**Comment by fleupold** [comment]
This seems to no longer be happening (a similar issue is captured in #684). Closing for now.
