### ISSUE TITLE
[event based orderbook] Measure test coverage

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#688]
And make sure that the event based orderbook's `State` has 100% branch coverage.

**Comment by e00E** [comment]
https://github.com/xd009642/tarpaulin
https://github.com/mozilla/grcov
https://github.com/SimonKagstrom/kcov

**Comment by e00E** [comment]
tarpaulin: works but doesn't have branch coverage and only works on Linux (not OSX)
grcov: doesn't work because it requires nightly
kcov: doesn't work because of a bug in cargo

https://github.com/rust-lang/compiler-team/issues/278 might be relevant in the future.

For now tarpaulin is the only option:
```
cargo install cargo-tarpaulin
cargo tarpaulin --out Html
firefox tarpaulin-report.html
```

**Comment by fleupold** [comment]
> grcov: doesn't work because it requires nightly

Could we just run nightly for the purpose of collecting a coverage report?

> kcov: doesn't work because of a bug in cargo

Do you have a link to an issue/description of that bug?

**Comment by e00E** [comment]
https://github.com/kennytm/cargo-kcov/issues/47

I'll try grcov with nightly but I don't like having to run nightly for it.

**Comment by fleupold** [comment]
> kennytm/cargo-kcov#47

This issue also involves nightly. Does it repro for stable cargo as well or does kcov also require nightly?

I'm fine with tarpaulin if it can run on travis (so that there is a way to browse the coverage when you are not on OSX). However, having branch coverage as part of the report would be very nice.

**Comment by e00E** [comment]
I get the same panic on stable, didn't notice that issue used nightly.

**Comment by e00E** [comment]
How you envision where the coverage is hosted @fleupold ?
I found the third party services https://coveralls.io/ and https://codecov.io/ that are apparently free for open source repositories. They host the coverage data for us and (probably) have a better UI that tracks changes over time.
Alternatively we could host the coverage html for single runs on something like our own s3 bucket. More work for us, probably worse UI.
Or let developers generate the coverage reports manually when they want to. This doesn't make CI slower but then the coverage tools have to be installed and working for your platform. I like this because the setup is the simplest but nothing stops us from doing this in addition to a hosted service.

**Comment by fleupold** [comment]
coveralls sounds good. We are already using this tool to measure the test coverage of our smart contracts on every PR (e.g. https://coveralls.io/builds/30751521)

Since running unit tests is quite fast (compared to building/e2e tests) I think it would be nice to get coverage reports on every build.
