### ISSUE TITLE
New price api: 1inch

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#720]
It would be valuable to include another price API:
https://1inch.exchange/#/ETH/aDAI

1. 1inch delivers prices for tokens that dex.ag does not support: e.g. aDAI.
2. In the case of dex.ag being down, we still get a price feed for the majority of the tokens.
3. With 3 price-feeds we can throw alerts if we don't get any price for one token without getting too much noise

**Comment by bh2smith** [comment]
This is a cool task, but not sure at the moment where the priority lies. This is directly related to #838 to generalize the `AveragePriceSource` which is labeled for cleanup. I am in the process of trying to make it a reality, which would aid in this integration task.
