### ISSUE TITLE
[event based orderbook] Use BigInt for balances in event based orderbook

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#750]
Nick has this idea. It would allow us to get rid of all (?) balance related overflow checks. Only when constructing the account states we would need to check that the number fits into a U256.
I want to look into this after the event based orderbook has been merged into master.
This BigInt library seems ok at first glance https://gitlab.com/tspiteri/rug .

**Comment by fleupold** [comment]
Is there a reason this is on hold? Can we make it part of our cleanup sprint?

**Comment by e00E** [comment]
I marked it as on hold initially because it was less important than the other tasks.

Arguments against this change are:
1. The library I linked has system dependencies on c libraries.
2. Code is slower (but speed is probably still no issue)

Arguments for this change are:
3. Code is smaller and simpler
4. Code is less accurate because we don't error early anymore in cases where we already know our assumptions with regards to the smart contract have been broken.
