### ISSUE TITLE
[event based orderbook] Avoid fetching block timestamp for past events

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#760]
The only way I see would be to handle past events slightly differently than future events, so for past events you apply all the events under the current batch ID (queried from the smart contract for example) and then for incoming events you can query the block timestamp for each (since they will be way more sparse).

Definitely a separate issue/PR though.

_Originally posted by @nlordell in https://github.com/gnosis/dex-services/pull/756#discussion_r413125454

**Comment by e00E** [comment]
The way described above doesn't work with the level of assumption verification we currently have where we check in some places that the batch id makes sense.

**Comment by fleupold** [comment]
The batchID is only really needed for Trades/Solutions/Reversions (which always come in the same block) and OrderCancellations. 

While we should probably add the batchId there in a future version of the smart contract, for now I think we would already do much better if we only queried the timestamps for this subset of events.

**Comment by e00E** [comment]
Idea:
We make the batch id in State optional. If it is there we verify all assumptions. If it is not there we do not verify any assumption related to batch id. When we a get a `SolutionSubmission` without a previous reverted trade we know that the previous solution got accepted and that the batch id has incremented by at least one which in turn allows us to apply pending deposits, proceeds, order used amounts.

**Comment by fleupold** [comment]
I like the idea!

Could we even directly apply all events that don't have a timestamp? We might have to keep the fee's stored somewhere but otherwise it would make sense to me to just directly add and subtract balances/used amounts since we would be guaranteed to not query state within one batch from any event without a timestamp.

However, the idea of simply omitting the assertions could be less intrusive and easier to implement. In that case, I'm all for it.

**Comment by fleupold** [comment]
Since we will need historic timestamp for "what if" analysis and historic price estimations, we want to keep the timestamps of all events. Thus this task is no longer relevant.
