### ISSUE TITLE
Alert when solver is stuck in negative utility for too long

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#814]
Hi,

within the solver team, we discussed that it would be very beneficial, to compare every newly calculated solution against the last one and throw an error if they are the same and non-trivial. This means that our solution was not accepted, due to a solver error - neg. utility - or driver error/timeouts. In any case, it would be good to get such a warning if we are generating the same solutions again.

**Comment by fleupold** [comment]
The issue with this is that most solutions include orders for EF, which are only valid for one batch.

It would also not catch errors/timeouts that happen before the solver is invoked. For negative utility we can differentiate the error already and could alert based on that.

**Comment by josojo** [comment]
Felix suggested detecting the unsubmitted solutions by searching for the same continuous benign errors (-neg utility) in logs.

We should coordinate with the DevOps to set up this new error alert system.
