### ISSUE TITLE
[GasEstimation] Don't double gas price if system time is past cutoff time for accepted solutions

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#825]
We currently double the gas price up to a maximum of 60 GWEI every two blocks regardless of what the current time is. 
In case we already passed the four minute mark up to which solutions are accepted we should probably not double the gas price but instead try to cancel the tx by sending a no-op tx with a slighty higher gas price to clear the tx queue.

https://github.com/gnosis/dex-services/blob/6f794300512e6332e1a80b4ad3ad6700f89fccf1/driver/src/solution_submission/mod.rs#L178-L190

**Comment by bh2smith** [comment]
Cool idea! I like the cancellation proposal!

**Comment by fleupold** [comment]
As described in https://github.com/gnosis/dex-services/issues/853 we should also not send the tx again if we didn't increase the gas price (due to the cap) as this leads to errors:

> 'submitSolution(uint32,uint256,address[],uint16[],uint128[],uint128[],uint16[]):(uint256)' failure: web3 error: RPC error: Error { code: ServerError(-32010), message: "Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.", data: None }

**Comment by nlordell** [comment]
Regarding #853, maybe there was something else going on as well, since if the last gas price is the gas cap, then we do not resubmit the solution.

I checked the logs and it looks like the solution was submitted twice, once with a gas price of 57500000001 and the second (and final) submission was with a gas price of 60000000000 (which is the gas cap).

**Comment by fleupold** [comment]
You are right @nlordell that this should not be an issue in our code. I missed the break condition. Let's discuss the actual root cause on the original issue then.

**Comment by fleupold** [comment]
Related task that I will close in favor of this one:

> This is regarding the following error:
https://gnosisinc.slack.com/archives/CQZBU9T5J/p1589080051000100
If the gas_cap has been reached, then we don't increase the nonce or the gas price anymore and we will get this error message.
Hence, the code should check whether we had already increased the gas price to gas_cap already beforehand, and if this happened, then we should not try to resubmit

In fact the code should also check that the increase >12.5% as otherwise parity doesn't accept the a transaction with the same nonce.
