### ISSUE TITLE
Convert script input to WEI

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#83]
The numbers we currently enter in our `.js` scripts (deposit/place order etc.) need to be scaled up by 10**18 to be in the right format for our driver (all values in the driver are expected to be wei and the optimizer doesn't work well with very tiny amounts). Since mongoDb doesn't seem to handle numbers >64bit we likely have to store values as strings, which will require some changes in the python code as well.

**Comment by bh2smith** [comment]
> Since mongoDb doesn't seem to handle numbers >64bit we likely have to store values as strings, which will require some changes in the python code as well.

This is going to be a nightmare...

**Comment by bh2smith** [comment]
I guess my question is, do we really need to change the scripts by multiplying amount by 10**18 or do we simply call the scripts with values like 

```js
truffle exec scripts/deposit.js  1 1 100000000000000000
```

**Comment by bh2smith** [comment]
Isn't this also going to require changes to the driver... This is starting to seem like a complete overhaul.

- Listener; store amounts as string (this will involve conversion of the integer emited from the contract to string)

- Driver; Parse DB query results from string and interpret them at uintXX

- Tests; Update all deposit and withdraw requests in shell scripts from 1, 2, 3 to 100000000000000000, 200000000000000000, 300000000000000000 etc...

**Comment by fleupold** [comment]
The driver part is already implemented as part of #80 (e.g. https://github.com/gnosis/dex-services/blob/38f977a5724973f0123a00ccfbfea4da64232ed8/driver/src/models.rs#L88). Feel free to use/copy that implementation.

I'd strongly suggest not to require the js scripts to take value with 18 zeros from the command-line, but instead use `web3.utils.toWei(amount_arg)` inside the script.

You are right that this touches a lot of components, but it turns out to be actually not that much code.

And it's really handy that we have a good set of e2e tests which allows finding the pieces that need adjustments quite quickly.

**Comment by bh2smith** [comment]
@fleupold - Do you think that state_index and slot (both also using `uint` in the contract) should also be stored in the DB as strings?

**Comment by fleupold** [comment]
Technically yes, but given that we can do 4 billions auctions before we would overflow them (with 3 minutes batch time that’s at least 12 billion minutes = ~25 years) we have some time before this becomes a practical issue.

**Comment by bh2smith** [comment]
At that point it will be like another Y2K scramble!
