### ISSUE TITLE
Split main into helpers

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#831]
Now that our main method handles a bunch of command line arguments, I think it would make sense if it were broken down in a few simple function calls, each of which that handles a logical component of the setup and running.

As an example breakdown, I would suggest taking each inline comment and offloading the few lines of code underneath into a method.

For example, I would call this `setup_metrics`

https://github.com/gnosis/dex-services/blob/5d496e996deca43a2e0131200fdb21464e0f4d41/driver/src/main.rs#L198-L205

**Comment by bh2smith** [comment]
After having taken a closer look at the implementation details of this task, it appears this code block used as an example was essentially the only thing that could be easily offloaded into a logical helper method. 

That is, without having to pass a bunch of individual `options` off into helper methods, this task might not actually be worth it. For example, another (possibly the only other) block that could potentially be broken out is the following:

https://github.com/gnosis/dex-services/blob/abd1ea9899fdc77a0346850e169d1f36abbd1289/driver/src/main.rs#L212-L226

which could turn into;

```js
    // Set up shared HTTP client and HTTP services.
    let http_factory = HttpFactory::new(options.http_timeout, http_metrics);
    let (web3, gas_station, price_oracle) = setup_http_services(http_factory);
```
where

```js
fn setup_http_services(http_factory: HttpFactory) -> (Web3, GnosisSafeGasStation, PriceOracle) {
    let web3 = web3_provider(
        &http_factory,
        options.node_url.as_str(), // <----- sucks to pass in
        options.rpc_timeout,       // <----- sucks to pass in
    )
    .unwrap();
    let gas_station = GnosisSafeGasStation::new(&http_factory, gas_station::DEFAULT_URI).unwrap();
    let price_oracle = PriceOracle::new(
        &http_factory,
        options.token_data,                    // <----- sucks to pass in
        options.price_source_update_interval,  // <----- sucks to pass in
    )
    .unwrap();
    (web3, gas_station, price_oracle)
}
```

I am going to close this in favour of other more relevant cleanup tasks.

**Comment by nlordell** [comment]
What is wrong with passing a reference to the `Options` struct around?

```rust
fn setup_http_services(http_factory: HttpFactory, options: &Options) -> (Web3, GnosisSafeGasStation, PriceOracle) {
    let web3 = web3_provider(
        &http_factory,
        options.node_url.as_str(), // <----- sucks to pass in
        options.rpc_timeout,       // <----- sucks to pass in
    )
    .unwrap();
    let gas_station = GnosisSafeGasStation::new(&http_factory, gas_station::DEFAULT_URI).unwrap();
    let price_oracle = PriceOracle::new(
        &http_factory,
        options.token_data,                    // <----- sucks to pass in
        options.price_source_update_interval,  // <----- sucks to pass in
    )
    .unwrap();
    (web3, gas_station, price_oracle)
}
```

**Comment by bh2smith** [comment]
> What is wrong with passing a reference to the Options struct around?

I could give it a try. I feel like I have tried this in the past and ran into some issues of "moving", but I guess references aren't moving so maybe this is fine! Will try again.

**Comment by nlordell** [comment]
I see, it could be that some `Options` fields require ownership. You might need to update the various constructors to either take these by reference as well, or use `.clone()` where appropriate.
