### ISSUE TITLE
Get rid of all `mod.rs` files

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#837]
For consistency, like `dexag` this price_estimation file should move its dedicated directory.

**Comment by nlordell** [comment]
I would argue we should get rid of all `mod.rs` files to be more in line with edition 2018.

**Comment by nlordell** [comment]
https://doc.rust-lang.org/stable/edition-guide/rust-2018/module-system/path-clarity.html#no-more-modrs

**Comment by bh2smith** [comment]
> I would argue we should get rid of all mod.rs files to be more in line with edition 2018.

I'm also ok this this. Just hoping we can make these two similar modules more consistent. With the new suggestion, I believe this task would be to rename `dexag/mod.rs` to `dexag.rs`

**Comment by nlordell** [comment]
Maybe the task should be to make the module paths consistent, i.e. `name/mod.rs` or `name.rs`.

**Comment by fleupold** [comment]
Renaming the issue to capture that this should apply to all mod.rs files
