### ISSUE TITLE
Can we use the solver without having to use its docker container?

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#841]
Can it be distributed as zip file, single binary or even c library?
That would make our docker set up a bit simpler.

**Comment by fleupold** [comment]
It requires c dependencies for the actual linear optimizer (gurobi or scip) which are platform dependent. This was the reason it's distributed as a docker.

We could however probably expose the open solver as a zip (assuming we also ship the python venv).

**Comment by fleupold** [comment]
Created https://github.com/gnosis/dex-open-solver/issues/67
