### ISSUE TITLE
Implement PriceEstimation Source based on price graph

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#842]
I understand why we do this (it helps the solver) but conceptually it doesn't make sense. The prices should be determined by the orderbook and not by some other exchange's orderbook.

**Comment by fleupold** [comment]
@koeppelmann also would like to see our price estimation from external sources disappear. 

I think as an interim step we can try to estimate prices using our own orderbook and the pricegraph approach that @nlordell implemented.

**Comment by nlordell** [comment]
Only thing to watch out for is whether or not prices can be manipulated this way. (Not saying the my can, just that we should consider this).

**Comment by bh2smith** [comment]
A nice suggestion made was to use a small amount of OWL when estimating prices (the minimum tradable amount). This would help with extreme slippage in estimations? Although, we may want to investigate if such an estimation might be misleading to the solver. 

Price estimation first reduces the orderbook by removing overlaps, and the resulting, non-overlapping, orderbook yields the price estimation.

**Comment by fleupold** [comment]
We need to implement a [PriceSource](https://github.com/gnosis/dex-services/blob/f1a0b703acb7512b767644415e12a2c6d1597b8e/core/src/price_estimation/price_source.rs#L61) that uses the internal pricegraph crate.

For this we can probably reuse the [`Orderbook` struct](https://github.com/gnosis/dex-services/blob/f1a0b703acb7512b767644415e12a2c6d1597b8e/price-estimator/src/orderbook.rs#L11) that @e00E implemented. I'd move this from the `price-estimator` into core.

The other part is to adjust the current price estimation to be performed on all tokens and not just a whitelisted subset of tokens (cf `tokens` passed around in `get_prices`). For this we would need to get the alias and decimals for each token. We could use [our Graph endpoint](https://thegraph.com/explorer/subgraph/gnosis/dfusion) for this, or if we don't want to depend on another service read it from the chain directly (requires more work and batch requests).

Alternatively we could make the TokenInfo part of source dependencies and not pass it in each invocation of `get_prices`. This would allow to keep the TokenInfo hardcoded and scoped to tokens we estimate via Kraken/Dex.AG. However, alias and decimals are also serialized into the [instance file](https://gnosis-dev-dfusion.s3.amazonaws.com/data/mainnet/best-ring-solver/instances/2020-06-02/instance_5303580_2020-06-02T05%3A06%3A28.016082323%2B00%3A00.json) and I'm not sure what would be the implications if we provide an estimate but no alias or decimals.

**Comment by e00E** [comment]
> I'd move this from the `price-estimator` into core.

I wouldn't do this yet, or if you do you might want to duplicate it. The current Orderbook in price-estimator is written with specific threading/locking behvior in mind that only holds for the price-estimator which is subject to change.
In `core` we already have the orderbooks from which you can create a pricegraph orderbook easily. Maybe just this part can be moved into core (core-orderbook -> pricegraph orderbook).
