### ISSUE TITLE
Become node agnostic

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#844]

**Comment by e00E** [comment]
This involves testing with geth and infura and maybe openethereum with default config.

**Comment by e00E** [comment]
I tested creating the event based orderbook and submitting a solution on Geth, Infura, OpenEthereum nodes provided by devops. Everything worked out of the box without any code changes.
I wasn't able to test our resubmitting with more gas code because it was not triggered.

**Comment by nlordell** [comment]
> I wasn't able to test our resubmitting with more gas code because it was not triggered.

I think the best way to test this would be to have the gas estimation use the "slow" price instead of "fast" so that it doesn't get mined right away.

**Comment by fleupold** [comment]
This would still require finding a solution (probably possible on rinkeby). I'm not too worried about solution submission. Can we still run the shadowed orderbook on the other nodes?

**Comment by e00E** [comment]
Tested that the filtered orderbook still works on the other nodes: it does. That means the shadow orderbook should work too because that is just what it does.

**Comment by fleupold** [comment]
What's the page size that works? Do you remember how long it roughly took with it?

**Comment by e00E** [comment]
I used the default page size of 100 with which it took 3 to 4 minutes. I didn't try to find the largest page size and fastest speed because that is not related to whether we are node agnostic and will depend on the specific node configuration and hardware.
I'll test it again to find those.

**Comment by fleupold** [comment]
I don't think that's necessary (also because it will change in the future as the data grows). I just wanted to document which size we know to work and could therefore use if needed 👍
