### ISSUE TITLE
Don't test rinkeby in CI

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#845]
This makes CI slower and rinkeby can be down which then makes CI fail.

Imo it is cleaner to test only with ganache but in practice. On the other hand this could mean that we miss an error that the test would have shown but I don't remember the last time it happened. But I do remember the test failing for no reason a bunch of times.

**Comment by fleupold** [comment]
I agree with this proposal. #697 #830 are related tasks. Let's discuss synchronously how we can improve our test setup to make it faster and less flaky.
