### ISSUE TITLE
test_ceiled_div_overflow_u128 fails on release mode

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#861]
https://github.com/gnosis/dex-services/blob/320a118cea27cfd66ddddb62d304a5cd696b6df6/driver/src/util.rs#L96

This test expects to panic but it only panics in debug mode because rust only checks for integer overflow in debug builds. With `cargo test --release` the test fails because the function does not panic.

**Comment by fleupold** [comment]
What would you suggest to do about it? Only run this test in debug mode or make the overflow check implicit in the implementation?

**Comment by e00E** [comment]
We don't use the this function where performance is critical so we can make the overflow check explicit (happens always). This seems to be what the test already expects.
