### ISSUE TITLE
Update travis ubuntu and node version

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#871]
The current ubuntu version used is Xenial but we can switch to Bionic.
The current node version is 10 but we can switch to 12.

**Comment by nlordell** [comment]
> The current ubuntu version used is Xenial but we can switch to Bionic.

I would just use the default OS, and we should probably explicitly set the NodeJS version to LTS.

**Comment by e00E** [comment]
I don't see why we wouldn't use the never ubuntu release on principle. I expect in general for things to work better on the newer release. The only reason we are using Xenial after all is because that is what travis happens to have picked for us.

**Comment by fleupold** [comment]
We used to build the rust binary inside travis and then copy it into the docker environment. Therefore our docker distribution and travis distribution need to be compatible (create the same binaries) which is why we pinned it., if I remember correctly

**Comment by nlordell** [comment]
>  which is why we pinned it

As far as I can tell it is currently not pinned to a distribution.

**Comment by e00E** [comment]
> We used to build the rust binary inside travis and then copy it into the docker environment.

This sounds like you expect that we no longer do this and instead rebuild in the container. This isn't the case from what I see in the build logs. We are still copying the binary over.

Here is the travis documentation for the build images:
https://docs.travis-ci.com/user/reference/xenial/
https://docs.travis-ci.com/user/reference/bionic/

There isn't a huge difference but I noticed that bionic comes with node 12 preinstalled so we wouldn't have to download it during build anymore.

**Comment by e00E** [comment]
@fleupold Tagging so you see the above message.

**Comment by fleupold** [comment]
My message was worded poorly, I was expecting we still do that today. 
I think the reason for running the tests natively in travis and not inside docker was so that it is a little less indirect and thus potentially easier to debug (also the docker image can really be minimal and doesn't have to install any rust or testing stuff).
