### ISSUE TITLE
[Pricegraph] Order amounts and user balance underflows

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#916]
Currently due to rounding errors, it is possible for an order amount or user balance to underflow because of rounding errors when sell token has a drastically different number of decimals than the other tokens being traded (such when selling USDC and going through tokens with the usual 18 decimals).

**Comment by fleupold** [comment]
What happens in this case? Do we panic or just provide incoherent data?

**Comment by e00E** [comment]
Just found this with fuzzing (had to fix a bug in fuzzing first, PR incoming):

```rust
    #[test]
    fn fuzz_error() {
        use crate::encoding::*;
        use primitive_types::{H160, U256};

        let mut orderbook = Orderbook::from_elements(vec![Element {
            user: H160::zero(),
            balance: U256::from_dec_str(
                "3532883802906008782403269293875209110100384173848976041480599189852671",
            )
            .unwrap(),
            pair: TokenPair { buy: 0, sell: 0 },
            valid: Validity {
                from: 285741312,
                to: 180095676,
            },
            price: Price {
                numerator: 13294906614391990988372451468773477386,
                denominator: 327042228921422829026657257798164547592,
            },
            remaining_sell_amount: 83798276971421254262445676335662107162,
            id: 2056,
        }]);
        orderbook.reduce_overlapping_orders();
    }
```

> panicked at 'remaining amount underflow for order 0x0000…0000-2056', pricegraph/src/orderbook.rs:364:13

Is this the same thing?

**Comment by nlordell** [comment]
> Is this the same thing?

Yes

**Comment by fleupold** [comment]
Unrelated to this issue but is there a way for us to integrate the fuzzing into some automated process? It feels like right now we rely on individuals running it after we think there might be an issue.

**Comment by nlordell** [comment]
> What happens in this case? Do we panic or just provide incoherent data?

In release mode (used by the Wasm module), nothing, the result might include rounding errors. Since (from what I remember) we apply a small "buffer" to these values in the front-end, at the end of the day, it shouldn't really matter.

In debug mode (used for tests and fuzzing) we panic.

**Comment by e00E** [comment]
> Unrelated to this issue but is there a way for us to integrate the fuzzing into some automated process? It feels like right now we rely on individuals running it after we think there might be an issue.

In my opinion fuzzing should be ran manually. Fuzzing doesn't prove the absence of bugs and you can run it for as long as possible. I wouldn't put in on travis because that is not what travis is made for and travis' cpu is slow.

**Comment by nlordell** [comment]
> I wouldn't put in on travis because that is not what travis is made for and travis' cpu is slow.

I completely agree, I don't think fuzzing should be part of CI.

> In my opinion fuzzing should be ran manually.

I think fuzzing can be run automatically, with a scheduled job for example. While I really don't think it should be run as part of CI, I see no issues with having it run automatically in some other context.

**Comment by e00E** [comment]
Sure, nothing wrong with automating it in general. It depends on how hard this is to set up. Not sure if it is worth to setup new infrastructure for this.

**Comment by e00E** [comment]
https://github.com/gnosis/dex-services/pull/922 related

**Comment by nlordell** [comment]
> #922 related

THanks for fixing, sorry I didn't notice :disappointed:

**Comment by fleupold** [comment]
@nlordell given this issue is becoming more blocking, do you have a suggestion of how to address this? We should probably try to tackle it early next week.

**Comment by nlordell** [comment]
I still don't 100% understand why this is happening :(. I can prioritize this next week Monday so at least I have a better idea of how to tackle it.

The reason I didn't think it was super important yet is:
- We can temporarily remove the debug assertions so this stops happening
- This is ultimately precision issues with using doubles, so I think it will always be there.

That being said I don't 100% understand the issue - so it might be worse than I am currently assuming.
