### ISSUE TITLE
Error retrieving orderbook

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#941]
I'm trying to run the driver with an Infura node and get the following panic on startup:
```
thread 'main' panicked at 'primary orderbook initialization failed: Batch RPC call to get block hashes failed

Caused by:
    Decoder error: Error("EOF while parsing a string", line: 1, column: 136176)', driver/src/main.rs:277:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Need to investigate more, but my initial suspicion is that there is some maximum to batched requests that can be made?

**Comment by e00E** [comment]
I remember this working when I tested different node configurations. Either I made a mistake in the test or Infura changed something.
To investigate more we would change the number of batch requests to see if that fixes the problem.

**Comment by nlordell** [comment]
Hmm, I'm getting the same error with our open ethereum nodes:
```
thread 'main' panicked at 'primary orderbook initialization failed: Batch RPC call to get block hashes failed

Caused by:
    Decoder error: Error("EOF while parsing a string", line: 1, column: 10354112)', driver/src/main.rs:277:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by e00E** [comment]
Works for me. You might have to increase RPC_TIMEOUT.

**Comment by nlordell** [comment]
Worked!
