### ISSUE TITLE
[Pricegraph] Exclude paths that do not meet additional exchange contraints

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#952]
This will cause the price estimator to produce a more conservative estimate and have the orderbook spread chart reflect a more conservative view of what is happening in the exchange between a given token pair.

The main motivation for this is to avoid a bad user experience where we show overlap for a market between a token pair that can't actually be matched because of some easily verifiable constraint.

Conversely, there is also the possible bad UX where a user places an order that doesn't show up in the orderbook spread chart. Maybe for direct orders that are ignored because of these verifiable contraints we can also provide a reason as to why it was ignored?

**Comment by fleupold** [comment]
Can you describe which constraints in particular you are referring to? Is this for economic viability and max number of trades per batch?

**Comment by nlordell** [comment]
The ones I had in mind were:
- Economic viability
- Min traded amount

I didn't plan on considering the maximum number of trades per batch, since the price estimate should still apply (although it would require multiple batches to trade).

**Comment by nlordell** [comment]
Min traded amount constraint is now respected - closing this in favour of #1024
