### ISSUE TITLE
slog-async: logger dropped messages due to channel overflow

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#960]
We see this from time to time in the alerts.

It is related to the buffer size we set in https://github.com/gnosis/dex-services/blob/d6dc38d10da682864d548ac7df5cc351e6d2a310/core/src/logging.rs#L21 https://docs.rs/slog-async/2.5.0/slog_async/struct.AsyncBuilder.html#method.chan_size .

However, looking at the logs clearly there are not 1024 messages coming in. I suspect that a library is generating a lot of log messages and the messages are only filtered after they reach async-logger.

The obvious solution is to increase the channel size but I wonder if we can do something better.

**Comment by fleupold** [comment]
I see that 1024 is described as the "channel size", but I wonder if this is equivalent to "number of messages" or "number of bytes" being logged. 1024 bytes would not be that much.

Also, might this be related to introducing a lot of async/await logic which might make the main thread more busy now and thus give the logger less chances to flush messages?

**Comment by e00E** [comment]
We talked about this in a meeting. We are going to increase the channel size.

Additionally I wonder this could be an improvement for slog-async so that it would filter by severity first and only then put messages on the channel.
