### ISSUE TITLE
[Price Estimation] Get price estimate/orderbooks for historic blockNumber/BatchId

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-services#967]
For various purposes it will be helpful to get a historical price quote based on the on-chain orderbook at that time. Some use cases are:

- Run a cronjob, that Identifies past orders placed with "reasonable prices" (prices that should have been matched according to the price estimation) but that did not result in a trade (one of our top level customer facing KPIs)
- Compare how good our prices to those of other DEXs by taking their past trades and comparing the achieved price with the price that GP would have offered at that time. 

I'd suggest to use the same endpoint as today, but provide an optional argument (e.g. `block` which could be a number or in the future even `pending` - for virtual order placement).

**Comment by cmagan** [comment]
It is also useful for analyzing market depth / slippage 
This will allow to compare to centralized exchanges as well and get a sense of real spreads and not just nominal spreads.
