### ISSUE TITLE
Change token ids in result from string to number

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#969]
Currently the token ids are returned as strings even though they are numbers. This is inline with the nodejs price estimator but it would be cleaner to have numbers.

We need to ask frontend if this would break their code.

**Comment by fleupold** [comment]
Cool, let's do it!

@anxolin @alfetopito do you know if changing the price estimation response from

> {"baseTokenId":"4","quoteTokenId":"1","buyAmountInBase":"239678524","sellAmountInQuote":"1000000000000000000"}

to 

> {"baseTokenId":4,"quoteTokenId":1,"buyAmountInBase":"239678524","sellAmountInQuote":"1000000000000000000"}

would break the frontend?

**Comment by alfetopito** [comment]
We don't use base/quote token ids response for anything on the frontend, even though we map them.

I suspect it won't break anything, but would be safer if we first tried on the rinkeby version, or any dev version that I can point my local version to.

**Comment by fleupold** [comment]
If it's easy enough to change the price estimator to localhost we could probably also just test it locally ourselves.

**Comment by alfetopito** [comment]
> If it's easy enough to change the price estimator to localhost we could probably also just test it locally ourselves.

Oh my, glad you asked. I have just the thing for you:

Set this custom config: https://github.com/gnosis/dex-react#dexpriceestimator

Instructions for creating the custom config https://github.com/gnosis/dex-react#config

Let me know in case anything is not clear in the readme.

**Comment by anxolin** [comment]
If it's useful, we can deploy a web pointing to any other URL. It would be as easy as creating a PR with the change and never merge. I think the PR can even be closed after we get the URL
