### ISSUE TITLE
Benchmark price estimator performance

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#977]
> Maybe in a follow up PR we can setup some service benchmarking so we start observing the performance impact of changes right away.

> Plus I would be interested in seeing how well this new service can handle concurrent client connections compared to the JS implementation

**Comment by nlordell** [comment]
In release more (with `opt-level=s`) I'm getting similar results to @e00E
```
Running 30s test @ http://localhost:8080/markets/1-7/estimated-buy-amount/1000000000000000000?atoms=true
5 connections

┌─────────┬──────┬──────┬───────┬──────┬─────────┬────────┬─────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev  │ Max     │
├─────────┼──────┼──────┼───────┼──────┼─────────┼────────┼─────────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │ 0.01 ms │ 0.1 ms │ 8.59 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴────────┴─────────┘
┌───────────┬─────────┬─────────┬───────┬────────┬──────────┬────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%   │ 97.5%  │ Avg      │ Stdev  │ Min     │
├───────────┼─────────┼─────────┼───────┼────────┼──────────┼────────┼─────────┤
│ Req/Sec   │ 12063   │ 12063   │ 13295 │ 15031  │ 13530.94 │ 904.58 │ 12060   │
├───────────┼─────────┼─────────┼───────┼────────┼──────────┼────────┼─────────┤
│ Bytes/Sec │ 2.73 MB │ 2.73 MB │ 3 MB  │ 3.4 MB │ 3.06 MB  │ 205 kB │ 2.73 MB │
└───────────┴─────────┴─────────┴───────┴────────┴──────────┴────────┴─────────┘
```

I also locally enabled logging for the route so I'm sure it is getting called. It is just taking ~200us per request :tada:

**Comment by e00E** [comment]
> One small think we can do to remove this outlier is to call `reduce_overlapping_orders` every time a new orderbook is constructed, that way the requests are handled with less latency.

This is already the case. I wouldn't worry about an 8 ms max time anyway.

**Comment by nlordell** [comment]
> I wouldn't worry about an 8 ms max time anyway.

Just want to understand the outlier.

**Comment by nlordell** [comment]
To really stress test the service, I ran `autocannon` with 1000 concurrent connections for 5 minutes:
```
Running 300s test @ http://localhost:8080/markets/1-7/estimated-buy-amount/100000000000000000000?atoms=true
1000 connections

┌─────────┬──────┬───────┬────────┬────────┬───────┬──────────┬────────────┐
│ Stat    │ 2.5% │ 50%   │ 97.5%  │ 99%    │ Avg   │ Stdev    │ Max        │
├─────────┼──────┼───────┼────────┼────────┼───────┼──────────┼────────────┤
│ Latency │ 3 ms │ 40 ms │ 163 ms │ 200 ms │ 51 ms │ 42.88 ms │ 1248.19 ms │
└─────────┴──────┴───────┴────────┴────────┴───────┴──────────┴────────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min    │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼────────┤
│ Req/Sec   │ 10695   │ 11375   │ 20943   │ 23311   │ 19420.7 │ 3485.85 │ 10442  │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼────────┤
│ Bytes/Sec │ 2.46 MB │ 2.62 MB │ 4.82 MB │ 5.36 MB │ 4.47 MB │ 802 kB  │ 2.4 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘
```

My CPU was maxed out: 

![image](https://user-images.githubusercontent.com/4210206/84361648-42c36080-abcc-11ea-96e7-d48c2dfaa88a.png)

Still, the average latency was 51ms, so the initial benchmarks look very promising. It also indicates that this service is very much CPU-bound at the moment - which is what I expected.

**Comment by e00E** [comment]
With the outlier, there are several levels on which this can happen. To see if your code is at fault we can try removing the mutex from the orderbook to exclude locking as the fault.
If we still get outliers it could be tokio's or warp's fault. To exclude that we could try a different executor or http framework.
If we still get outliers it could be the operating system so we can try running the same program on different OSes with roughly the same hardware.
As I said, I don't think it's worth to look into this at this point, just throwing out some ideas.

If your CPU is close to getting maxed out which could already happen with a concurrency level
close to the number of threads of your cpu then I already expect outliers just from OS level scheduling and other program running.

**Comment by nlordell** [comment]
> As I said, I don't think it's worth to look into this at this point, just throwing out some ideas.

I think you're right.
