### ISSUE TITLE
Deploy in release mode

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#992]
We have been building the driver binary in debug mode for the deployed docker images. This was never a problem because there was no cpu intensive work.

Recently we got the event based orderbook, which in it's current version re-creates the whole orderbook from scratch every batch based on all past events. We're also going to start using the pricegraph to estimate prices in #990 .
Both of these operations are cpu intensive and while I don't think the time they take is a problem yet we might want do be future proof by building in release mode which should make them significantly faster.

advantages:
* everything is faster and more efficient in terms of cpu usage

disadvantages:
* deploy step takes longer because compiling in release mode takes longer

Another difference is that we lose implicit integer overflow checks that are only enabled in debug mode. This hasn't ever happened and we shouldn't be relying on implicit checks like this in the first place (and as far as I'm aware, we don't).

The change should be very simple: add `--release` to `cargo build --locked -p driver` in travis but I'm looking for other opinions on this issue.

**Comment by nlordell** [comment]
I think you can configure release mode to build with overflow checks.

**Comment by fleupold** [comment]
Release build would give us less debug information in cases of crashes, right? I don't think we are crashing a lot, so this might not be an issue. We could also consider building our tags with release and have latest in debug mode.

**Comment by nlordell** [comment]
> Release build would give us less debug information in cases of crashes, right?

Just checked and it looks like we get full back traces in release mode:
```
   Compiling playground v0.0.1 (/playground)
    Finished release [optimized] target(s) in 1.13s
     Running `target/release/playground`
thread 'main' panicked at 'test', src/main.rs:2:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
...
```

From the reference https://doc.rust-lang.org/cargo/reference/profiles.html it looks like release turns on more optimizations, turns off incremental building and sets opt-level to 3. These make the compilation take longer but in theory help produce faster code (:+1:)

Additionally, in release mode, `debug_assertions` and overflow checking is disabled, this could potentially cause some differences as `debug_assert!`s will be ignored and we won't panic on overflow (:-1) (note that if we want we can enable both or one of these with:)
```toml
[profile.release]
debug-assertions = true
overflow-checks = true
```

The last thing is it string out debug information. Note that it still generates stack unwind guards (`panic = "unwind"` is enabled in debug and release mode), so we still get a backtrace on panic, its just that if we attach a debugger, it won't have any idea what binary code corresponds to what Rust code.

**Comment by e00E** [comment]
I made a PR to enable release mode.

My conclusion is that this is the reasonable thing to do by default. With rust projects it is expected that the releases do not have debug assertions and implicit overflow checks. If we wanted to have them we should turn them into real asserts and explicit overflow checks. So far these checks have never triggered in the driver to my knowledge.

There is an argument for running with those checks in staging but it is a bit more complicated so let's do the reasonable small thing first and just enable release mode and then we can discuss that more
