### ISSUE TITLE
Transitive orders that are overlapping can get considered more than once.

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#999]
There is an issue with the current algorithm where transitive orders may be considered more than once if they are part of more than one negative cycle. This leads to incorrect reporting of transitive orders and inflates the actual available volume to the system.

**Comment by fleupold** [comment]
How exactly does that happen? Don't we remove negative cycles as we encounter them?

**Comment by nlordell** [comment]
The reason is the same orders might be part of multiple cycles. Currently when we find a cycle, we calculate two transitive orders from the cycle and then reduce the cycle. Really, we should be reducing the transitive orders.

**Comment by fleupold** [comment]
> Currently when we find a cycle, we calculate two transitive orders from the cycle and then reduce the cycle.

So in this case the order is gone from the orderbook, right? I don't understand how they can show up in multiple cycles?

Or is this regarding estimations across different token pairs (between which we reset the orderbook to be unreduced). This would however not only relate to the overlapping part but to all transitive orders, wouldn't it?

**Comment by nlordell** [comment]
> So in this case the order is gone from the orderbook, right? I don't understand how they can show up in multiple cycles?

Only the overlapping volume is gone from the orderbook when a negative cycle is reduced (or else a small market order would eat up an entire market-maker's order for price estimates).

So if you imagine an orderbook:
- Order 1 buy 2.0 token 1 for 4.0 token 2
- Order 2 buy 1.0 token 2 for 1.0 token 1
- Order 3 buy 1.5 token 1 for 1.0 token 1

Order 1 overlaps with orders 2 and 3, so previously when computing the overlapping transitive orderbook for market 1-2 we would add
- Order 1 buy 2.0 token 1 for 4.0 token 2 to the "asks"
- Order 2 buy 1.0 token 2 for 1.0 token 1 to the "bids"

Then reduce the orderbook's negative cycle so using limit prices, so:
So if you imagine an orderbook:
- Order 1 buy 1.0 token 1 for 2.0 token 2
- Order 3 buy 1.5 token 1 for 1.0 token 1

Then there would be another negative cycle and we would add:
- Order 1 buy 1.0 token 1 for 2.0 token 2 to the "asks"
- Order 3 buy 1.5 token 2 for 1.0 token 1 to the "bids"

And our resulting transitive orderbook would incorrectly state that there are 2 ask transitive orders!

There are two solutions that immediately come to mind:
1. The easier solution is to reduce the discovered overlapping orders, this way, after finding the initial negative cycle we would only be left with order 3.
2. The harder solution is to compute the "effective" transitive order, i.e. how much of the full transitive order can actually be filled by the mirror transitive order in the negative cycle, and add that to transitive orderbook instead of the full order.

I went with 1 because it is easier, and intuitively, the entire order will be included (either because of more negative cycles) or when the rest (i.e. non-overlapping) part of the transitive orderbook is calculated. Also, this way, one "full" or "actual" transitive order doesn't get split into "effective sub-" transitive order. The downside is that the spread calculation will become more imprecise (since we aren't properly reducing the overlap, but rather reducing complete orders that are part of this overlap).
